#  5147 data wrangle

In [3]:
import pandas as pd

In [2]:
df_1= pd.read_csv('A.csv')

In [7]:
df_1

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Special Notes,Region,Income Group,WB-2 code,...,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Unnamed: 30
0,ABW,Aruba,Aruba,Aruba,AW,Aruban florin,Central Bureau of Statistics and Central Bank ...,Latin America & Caribbean,High income,AW,...,NaN,Enhanced General Data Dissemination System (e-...,2010,NaN,NaN,Yes,NaN,NaN,2016.0,NaN
1,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Central Statistics Organization; World Bank st...,South Asia,Low income,AF,...,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2017.0,NaN
2,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,IMF ; Source of population estimates: UN Popul...,Sub-Saharan Africa,Lower middle income,AO,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2014,"Demographic and Health Survey, 2015/16","Integrated household survey (IHS), 2008/09",NaN,NaN,NaN,2017.0,NaN
3,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,Albanian Institute of Statistics ; Source of p...,Europe & Central Asia,Upper middle income,AL,...,Consolidated central government,Enhanced General Data Dissemination System (e-...,2011,"Demographic and Health Survey, 2017/18",Living Standards Measurement Study Survey (LSM...,Yes,2012,2013.0,2017.0,NaN
4,AND,Andorra,Andorra,Principality of Andorra,AD,Euro,"Government of Andorra, Department of Statistic...",Europe & Central Asia,High income,AD,...,NaN,NaN,2011. Population data compiled from administra...,NaN,NaN,Yes,NaN,NaN,NaN,NaN
5,ARB,Arab World,Arab World,Arab World,1A,NaN,Arab World aggregate. Arab World is composed o...,NaN,NaN,1A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016.0,NaN
6,ARE,United Arab Emirates,United Arab Emirates,United Arab Emirates,AE,U.A.E. dirham,National Bureau of Statistics & Federal Compet...,Middle East & North Africa,High income,AE,...,Consolidated central government,Enhanced General Data Dissemination System (e-...,2010,"World Health Survey, 2003",NaN,NaN,2012,1985.0,2017.0,NaN
7,ARG,Argentina,Argentina,Argentine Republic,AR,Argentine peso,National Institute of Statistics and Census (I...,Latin America & Caribbean,High income,AR,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2010,"Multiple Indicator Cluster Survey, 2011/12","Integrated household survey (IHS), 2016",Yes,2008,2002.0,2017.0,NaN
8,ARM,Armenia,Armenia,Republic of Armenia,AM,Armenian dram,National Statistical Service of the Republic o...,Europe & Central Asia,Upper middle income,AM,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2011,"Demographic and Health Survey, 2015/16","Integrated household survey (IHS), 2016",Yes,2014,NaN,2017.0,NaN
9,ASM,American Samoa,American Samoa,American Samoa,AS,U.S. dollar,BEA: https://www.bea.gov/national/gdp_territor...,East Asia & Pacific,Upper middle income,AS,...,NaN,NaN,2010,NaN,NaN,Yes,2008,NaN,2017.0,NaN
10,ATG,Antigua and Barbuda,Antigua and Barbuda,Antigua and Barbuda,AG,East Caribbean dollar,Eastern Caribbean Central Bank ; Source of pop...,Latin America & Caribbean,High income,AG,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2011,NaN,NaN,Yes,2007,NaN,2017.0,NaN
11,AUS,Australia,Australia,Commonwealth of Australia,AU,Australian dollar,ABS (Australian Bureau of Statistics) ; Source...,East Asia & Pacific,High income,AU,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2016,NaN,"Expenditure survey/budget survey (ES/BS), 2010",Yes,2015-2016,2013.0,2017.0,NaN
12,AUT,Austria,Austria,Republic of Austria,AT,Euro,OECD (Organization for Economic Cooperation an...,Europe & Central Asia,High income,AT,...,Consolidated central government,Special Data Dissemination Standard Plus (SDDS+),2011. Population data compiled from administra...,NaN,"Income survey (IS), 2015",Yes,2010,2014.0,2017.0,NaN
13,AZE,Azerbaijan,Azerbaijan,Republic of Azerbaijan,AZ,New Azeri manat,The State Statistical Committee of the Republi...,Europe & Central Asia,Upper middle income,AZ,...,Consolidated central government,Enhanced General Data Dissemination System (e-...,2009,"Demographic and Health Survey, 2006",Living Standards Measurement Study Survey (LSM...,Yes,2015,2013.0,2017.0,NaN
14,BDI,Burundi,Burundi,Republic of Burundi,BI,Burundi franc,Statistical Office Burundi and World Bank coun...,Sub-Saharan Africa,Low income,BI,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2008,"Demographic and Health Survey, 2016/17",Core Welfare Indicator Questionnaire Survey (C...,Yes,NaN,2012.0,2017.0,NaN
15,BEL,Belgium,Belgium,Kingdom of Belgium,BE,Euro,OECD (Organization for Economic Cooperation an...,Europe & Central Asia,High income,BE,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2011. Population data compiled from administra...,NaN,"Income survey (IS), 2015",Yes,2010,2014.0,2017.0,NaN
16,BEN,Benin,Benin,Republic of Benin,BJ,West African CFA franc,Government of Benin ; Source of population es...,Sub-Saharan Africa,Low income,BJ,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2013,"Demographic and Health Survey, 2017/18",Core Welfare Indicator Questionnaire Survey (C...,NaN,NaN,1981.0,2017.0,NaN
17,BFA,Burkina Faso,Burkina Faso,Burkina Faso,BF,West African CFA franc,National forecast tool (Instrument Automatise ...,Sub-Saharan Africa,Low income,BF,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2006,"Malaria Indicator Survey, 2017/18",Core Welfare Indicator Questionnaire Survey (C...,NaN,2006-2010,1983.0,2017.0,NaN
18,BGD,Bangladesh,Bangladesh,People's Republic of Bangladesh,BD,Bangladeshi taka,National Account Data from Bangladesh Bureau o...,South Asia,Lower middle income,BD,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2011,"Demographic and Health Survey, 2017/18","Integrated household survey (IHS), 2016",NaN,2008,2011.0,2017.0,NaN
19,BGR,Bulgaria,Bulgaria,Republic of Bulgaria,BG,Bulgarian lev,Eurostat & Republic of Bulgaria National Stati...,Europe & Central Asia,Upper middle income,BG,...,Consolidated central government,Special Data Dissemination Standard Plus (SDDS+),2011,"Living Standards Measurement Study, 2007","Expenditure survey/budget survey (ES/BS), 2014",Yes,2010,2014.0,2017.0,NaN
20,BHR,Bahrain,Bahrain,Kingdom of Bahrain,BH,Bahraini dinar,Central Bank of Bahrain & Cetral Informatic Or...,Middle East & North Africa,High income,BH,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2010. Population data compiled from administra...,NaN,NaN,Yes,2010,2013.0,2017.0,NaN
21,BHS,The Bahamas,"Bahamas, The",Commonwealth of The Bahamas,BS,Bahamian dollar,Department of Statistics of Bahamas ; Source o...,Latin America & Caribbean,High income,BS,...,Consolidated central government,Enhanced General Data Dissemination System (e-...,2010,NaN,NaN,NaN,NaN,1998.0,2017.0,NaN
22,BIH,Bosnia and Herzegovina,Bosnia and Herzegovina,Bosnia and Herzegovina,BA,Bosnia and Herzegovina convertible mark,Agency for Statistics of Bosnia and Herzegovin...,Europe & Central Asia,Upper middle income,BA,...,Consolidated central government,Enhanced General Data Dissemination System (e-...,2013,"Multiple Indicator Cluster Survey, 2011/12","Expenditure survey/budget survey (ES/BS), 2015",Yes,NaN,2011.0,2017.0,NaN
23,BLR,Belarus,Belarus,Republic of Belarus,BY,Belarusian rubel,National Statistical Committee of the Republic...,Europe & Central Asia,Upper middle income,BY,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2009,"Multiple Indicator Cluster Survey, 2012","Integrated household survey (IHS), 2017",Yes,NaN,2014.0,2017.0,NaN
24,BLZ,Belize,Belize,Belize,BZ,Belize dollar,Central Bank of Belize ; Source of population ...,Latin America & Caribbean,Upper middle income,BZ,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2010,"Multiple Indicator Cluster Survey, 2015/16","Labor force survey (LFS), 1999",NaN,2011,1992.0,2017.0,NaN
25,BMU,Bermuda,Bermuda,The Bermudas,BM,Bermuda dollar,Source of population estimates: Bermuda Govern...,North America,High income,BM,...,NaN,NaN,2010,NaN,NaN,Yes,NaN,NaN,2017.0,NaN
26,BOL,Bolivia,Bolivia,Plurinational State of Bolivia,BO,Bolivian Boliviano,National Institute of Statistics (INE) and Cen...,Latin America & Caribbean,Lower middle income,BO,...,NaN,Enhanced General Data Dissemination System (e-...,2012,"Demographic and Health Survey, 2008","Integrated household survey (IHS), 2016",NaN,2013,2010.0,2017.0,NaN
27,BRA,Brazil,Brazil,Federative Republic of Brazil,BR,Brazilian real,Brazilian Statistics Institute (IBGE) ; Source...,Latin America & Caribbean,Upper middle income,BR,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2010,"National Health Survey, 2013","Integrated household survey (IHS), 2016",Yes,2006,2013.0,2017.0,NaN
28,BRB,Barbados,Barbados,Barbados,BB,Barbados dollar,Barbados Statistical Office ; Source of popula...,Latin America & Caribbean,High income,BB,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2010,"Multiple Indicator Cluster Survey, 2012",NaN,Yes,NaN,1997.0,2017.0,NaN
29,BRN,Brunei,Brunei Darussalam,Brunei Darussalam,BN,Brunei dollar,Economic Planning and Development - Prime Mini...,East Asia & Pacific,High income,BN,...,NaN,Enhanced General Data Dissemination System (e-...,2011,NaN,NaN,Yes,NaN,NaN,2017.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,TLA,Latin America & Caribbean (IDA & IBRD),Latin America & Caribbean (IDA & IBRD),Latin America & Caribbean (IDA & IBRD),T2,NaN,Latin America & the Caribbean (IDA & IBRD coun...,NaN,NaN,T2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016.0,NaN
234,TLS,Timor-Leste,Timor-Leste,Democratic Republic of Timor-Leste,TL,U.S. dollar,Timor -Leste National Accounts from General di...,East Asia & Pacific,Lower middle income,TP,...,NaN,Enhanced General Data Dissemination System (e-...,2015,"Demographic and Health Survey, 2016",Living Standards Measurement Study Survey (LSM...,NaN,NaN,NaN,2017.0,NaN
235,TMN,Middle East & North Africa (IDA & IBRD),Middle East & North Africa (IDA & IBRD),Middle East & North Africa (IDA & IBRD),T3,NaN,Middle East & North Africa (IDA & IBRD countri...,NaN,NaN,T3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016.0,NaN
236,TON,Tonga,Tonga,Kingdom of Tonga,TO,Tongan pa'anga,Tonga Department of Statistics ; Source of pop...,East Asia & Pacific,Upper middle income,TO,...,Consolidated central government,Enhanced General Data Dissemination System (e-...,2016,"Demographic and Health Survey, 2012","Integrated household survey (IHS), 2009",NaN,2015,1981.0,2017.0,NaN
237,TSA,South Asia (IDA & IBRD),South Asia (IDA & IBRD),South Asia (IDA & IBRD),T5,NaN,South Asia (IDA & IBRD countries) aggregate.,NaN,NaN,T5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016.0,NaN
238,TSS,Sub-Saharan Africa (IDA & IBRD),Sub-Saharan Africa (IDA & IBRD),Sub-Saharan Africa (IDA & IBRD),T6,NaN,Sub-Saharan Africa (IDA & IBRD countries) aggr...,NaN,NaN,T6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016.0,NaN
239,TTO,Trinidad and Tobago,Trinidad and Tobago,Republic of Trinidad and Tobago,TT,Trinidad and Tobago dollar,Central Bank of Trinidad and Tobago ; Source o...,Latin America & Caribbean,High income,TT,...,NaN,Enhanced General Data Dissemination System (e-...,2011,"Multiple Indicator Cluster Survey, 2011","Integrated household survey (IHS), 1992",Yes,NaN,2006.0,2017.0,NaN
240,TUN,Tunisia,Tunisia,Republic of Tunisia,TN,Tunisian dinar,"National Bureau of Statistics, Central Bank, M...",Middle East & North Africa,Lower middle income,TN,...,Budgetary central government,Special Data Dissemination Standard (SDDS),2014,"Demographic and Health Survey, 2018","Integrated household survey (IHS), 2015",NaN,NaN,2010.0,2017.0,NaN
241,TUR,Turkey,Turkey,Republic of Turkey,TR,New Turkish lira,Turkish Statistical Institute ; Source of popu...,Europe & Central Asia,Upper middle income,TR,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2011. Population data compiled from administra...,"Demographic survey, 2018","Expenditure survey/budget survey (ES/BS), 2016",Yes,NaN,2014.0,2017.0,NaN
242,TUV,Tuvalu,Tuvalu,Tuvalu,TV,Australian dollar,IMF Article IV and The US Graduate School (pit...,East Asia & Pacific,Upper middle income,TV,...,NaN,Enhanced General Data Dissemination System (e-...,2012,"Demographic and Health Survey, 2007","Expenditure survey/budget survey (ES/BS), 2010",NaN,NaN,NaN,2017.0,NaN
243,TZA,Tanzania,Tanzania,United Republic of Tanzania,TZ,Tanzanian shilling,Tanzania Bureau of Statistics ; Source of popu...,Sub-Saharan Africa,Low income,TZ,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2012,"Malaria Indicator Survey, 2017","Expenditure survey/budget survey (ES/BS), 2011/12",NaN,2007-2008,2010.0,2017.0,NaN
244,UGA,Uganda,Uganda,Republic of Uganda,UG,Ugandan shilling,"Uganda Bureau of Statistics for SNA series , B...",Sub-Saharan Africa,Low income,UG,...,Consolidated central government,Enhanced General Data Dissemination System (e-...,2014,"Malaria Indicator Survey, 2018/19","Integrated household survey (IHS), 2015/16",NaN,2008-2009,2000.0,2017.0,NaN
245,UKR,Ukraine,Ukraine,Ukraine,UA,Ukrainian hryvnia,State Statistics Committee of Ukraine ; Source...,Europe & Central Asia,Lower middle income,UA,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2001,"Multiple Indicator Cluster Survey, 2012","Integrated household survey (IHS), 2017",Yes,NaN,2014.0,2017.0,NaN
246,UMC,Upper middle income,Upper middle income,Upper middle income,XT,NaN,Upper middle income group aggregate. Upper-mid...,NaN,NaN,XT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016.0,NaN
247,URY,Uruguay,Uruguay,Oriental Republic of Uruguay,UY,Uruguayan peso,Central Bank of Uruguay ; Source of population...,Latin America & Caribbean,High income,UY,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2011,"Multiple Indicator Cluster Survey, 2012/13","Integrated household survey (IHS), 2017",Yes,2011,2011.0,2017.0,NaN
248,USA,United States,United States,United States of America,US,U.S. dollar,OECD (Organization for Economic Cooperation an...,North America,High income,US,...,Consolidated central government,Special Data Dissemination Standard Plus (SDDS+),2010,NaN,"Labor force survey (LFS), 2016",Yes,2012,2011.0,2016.0,NaN
249,UZB,Uzbekistan,Uzbekistan,Republic of Uzbekistan,UZ,Uzbek sum,The State Committee of the Republic of Uzbekis...,Europe & Central Asia,Lower middle income,UZ,...,Consolidated central government,Enhanced General Data Dissemination System (e-...,1989,"Multiple Indicator Cluster Survey, 2006","Expenditure survey/budget survey (ES/BS), 2013",Yes,NaN,NaN,2017.0,NaN
250,VCT,St. Vincent and the Grenadines,St. Vincent and the Grenadines,St. Vincent and the Grenadines,VC,East Caribbean dollar,Eastern Caribbean Central Bank ; Source of pop...,Latin America & Caribbean,Upper middle income,VC,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2012,NaN,NaN,Yes,NaN,NaN,2017.0,NaN
251,VEN,Venezuela,"Venezuela, RB",República Bolivariana de Venezuela,VE,Venezuelan bolivar fuerte,Central Bank of Venezuela ; Source of populati...,Latin America & Caribbean,Upper middle income,VE,...,NaN,Enhanced General Data Dissemination System (e-...,2011,"Multiple Indicator Cluster Survey, 2000","Integrated household survey (IHS), 2015",NaN,2008,1998.0,2016.0,NaN
252,VGB,British Virgin Islands,British Virgin Islands,British Virgin Islands,VG,U.S. dollar,NaN,Latin America & Caribbean,High income,VG,...,NaN,NaN,2010,"STEPS Risk Factor Survey, 2010",NaN,Yes,NaN,NaN,NaN,NaN
253,VIR,Virgin Islands,Virgin Islands (U.S.),Virgin Islands of the United States,VI,U.S. dollar,Source of population estimates: U.S. Census Bu...,Latin America & Caribbean,High income,VI,...,NaN,NaN,2010,NaN,NaN,Yes,2012,NaN,NaN,NaN
254,VNM,Vietnam,Vietnam,Socialist Republic of Vietnam,VN,Vietnamese dong,GSO (General Statistics Office of Vietnam) and...,East Asia & Pacific,Lower middle income,VN,...,NaN,Enhanced General Data Dissemination System (e-...,2009,"Multiple Indicator Cluster Survey, 2013/14","Integrated household survey (IHS), 2016",Yes,2016,2013.0,2017.0,NaN
255,VUT,Vanuatu,Vanuatu,Republic of Vanuatu,VU,Vanuatu vatu,IMF Article IV ; Source of population estimat...,East Asia & Pacific,Lower middle income,VU,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2016,Vanuatu Demographic and Health Survey/Multiple...,"Integrated household survey (IHS), 2010",NaN,2007,NaN,2017.0,NaN
256,WLD,World,World,World,1W,NaN,World aggregate.,NaN,NaN,1W,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016.0,NaN
257,WSM,Samoa,Samoa,Samoa,WS,Samoan tala,IMF Article IV and Bank's country office ; Sou...,East Asia & Pacific,Upper middle income,WS,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2016,"Samoa Demographic and Health Survey, 2014","Expenditure survey/budget survey (ES/BS), 2013",NaN,2009,NaN,2017.0,NaN
258,XKX,Kosovo,Kosovo,Republic of Kosovo,XK,Euro,Kosovo Agency of Statistics ; Source of popula...,Europe & Central Asia,Lower middle income,XK,...,NaN,Enhanced General Data Dissemination System (e-...,2011,"Multiple Indicator Cluster Survey, 2013/14","Expenditure survey/budget survey (ES/BS), 2015",NaN,2014,NaN,NaN,NaN
259,YEM,Yemen,"Yemen, Rep.",Republic of Yemen,YE,Yemeni rial,Figures are based on MFMmod data ; Source of ...,Middle East & North Africa,Low income,RY,...,NaN,Enhanced General Data Dissemination System (e-...,2004,"Demographic and Health Survey, 2013","Expenditure survey/budget survey (ES/BS), 2014",NaN,NaN,2012.0,2017.0,NaN
260,ZAF,South Africa,South Africa,Republic of South Africa,ZA,South African rand,(see also: https://www.imf.org/en/News/Article...,Sub-Saharan Africa,Upper middle income,ZA,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2011,"Demographic and Health Survey, 2016","Expenditure survey/budget survey (ES/BS), 2014/15",NaN,2007,2010.0,2017.0,NaN
261,ZMB,Zambia,Zambia,Republic of Zambia,ZM,New Zambian kwacha,"Central Statistics Office Zambia, Bank of Zamb...",Sub-Saharan Africa,Lower middle income,ZM,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2010,"Demographic and Health Survey, 2013/14","Integrated household survey (IHS), 2015",NaN,NaN,1994.0,2017.0,NaN
262,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,U.S. dollar,Zimstat- Central Statistics Agency ; Source of...,Sub-Saharan Africa,Low income,ZW,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2012,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2011/12",NaN,NaN,NaN,2017.0,NaN

In [4]:
df_2= pd.read_csv('B.csv')

In [5]:
df_2.head()

,Series,Series Code,Country Name,Country Code,1990 [YR1990],2000 [YR2000],2055 [YR2055],2060 [YR2060],2065 [YR2065],2070 [YR2070],2075 [YR2075],2080 [YR2080],2085 [YR2085],2090 [YR2090],2095 [YR2095],2100 [YR2100]
0,Share of female students in upper secondary ed...,UIS.GTVP.3.GPV.F,Arab World,ARB,..,68.52861,..,..,..,..,..,..,..,..,..,..
1,Share of female students in upper secondary ed...,UIS.GTVP.3.GPV.F,Caribbean small states,CSS,..,..,..,..,..,..,..,..,..,..,..,..
2,Share of female students in upper secondary ed...,UIS.GTVP.3.GPV.F,Central Europe and the Baltics,CEB,..,..,..,..,..,..,..,..,..,..,..,..
3,Share of female students in upper secondary ed...,UIS.GTVP.3.GPV.F,Early-demographic dividend,EAR,..,..,..,..,..,..,..,..,..,..,..,..
4,Share of female students in upper secondary ed...,UIS.GTVP.3.GPV.F,East Asia & Pacific,EAS,..,58.88179,..,..,..,..,..,..,..,..,..,..

In [12]:
df_3= pd.read_csv('E.csv')

In [13]:
df_3

,Country Code,Region,IncomeGroup,SpecialNotes,TableName,Unnamed: 5
0,ABW,Latin America & Caribbean,High income,Central Bureau of Statistics and Central Bank ...,Aruba,NaN
1,AFG,South Asia,Low income,Central Statistics Organization; World Bank st...,Afghanistan,NaN
2,AGO,Sub-Saharan Africa,Lower middle income,IMF ; Source of population estimates: UN Popul...,Angola,NaN
3,ALB,Europe & Central Asia,Upper middle income,Albanian Institute of Statistics ; Source of p...,Albania,NaN
4,AND,Europe & Central Asia,High income,"Government of Andorra, Department of Statistic...",Andorra,NaN
5,ARB,NaN,NaN,Arab World aggregate. Arab World is composed o...,Arab World,NaN
6,ARE,Middle East & North Africa,High income,National Bureau of Statistics & Federal Compet...,United Arab Emirates,NaN
7,ARG,Latin America & Caribbean,High income,National Institute of Statistics and Census (I...,Argentina,NaN
8,ARM,Europe & Central Asia,Upper middle income,National Statistical Service of the Republic o...,Armenia,NaN
9,ASM,East Asia & Pacific,Upper middle income,BEA: https://www.bea.gov/national/gdp_territor...,American Samoa,NaN
10,ATG,Latin America & Caribbean,High income,Eastern Caribbean Central Bank ; Source of pop...,Antigua and Barbuda,NaN
11,AUS,East Asia & Pacific,High income,ABS (Australian Bureau of Statistics) ; Source...,Australia,NaN
12,AUT,Europe & Central Asia,High income,OECD (Organization for Economic Cooperation an...,Austria,NaN
13,AZE,Europe & Central Asia,Upper middle income,The State Statistical Committee of the Republi...,Azerbaijan,NaN
14,BDI,Sub-Saharan Africa,Low income,Statistical Office Burundi and World Bank coun...,Burundi,NaN
15,BEL,Europe & Central Asia,High income,OECD (Organization for Economic Cooperation an...,Belgium,NaN
16,BEN,Sub-Saharan Africa,Low income,Government of Benin ; Source of population es...,Benin,NaN
17,BFA,Sub-Saharan Africa,Low income,National forecast tool (Instrument Automatise ...,Burkina Faso,NaN
18,BGD,South Asia,Lower middle income,National Account Data from Bangladesh Bureau o...,Bangladesh,NaN
19,BGR,Europe & Central Asia,Upper middle income,Eurostat & Republic of Bulgaria National Stati...,Bulgaria,NaN
20,BHR,Middle East & North Africa,High income,Central Bank of Bahrain & Cetral Informatic Or...,Bahrain,NaN
21,BHS,Latin America & Caribbean,High income,Department of Statistics of Bahamas ; Source o...,"Bahamas, The",NaN
22,BIH,Europe & Central Asia,Upper middle income,Agency for Statistics of Bosnia and Herzegovin...,Bosnia and Herzegovina,NaN
23,BLR,Europe & Central Asia,Upper middle income,National Statistical Committee of the Republic...,Belarus,NaN
24,BLZ,Latin America & Caribbean,Upper middle income,Central Bank of Belize ; Source of population ...,Belize,NaN
25,BMU,North America,High income,Source of population estimates: Bermuda Govern...,Bermuda,NaN
26,BOL,Latin America & Caribbean,Lower middle income,National Institute of Statistics (INE) and Cen...,Bolivia,NaN
27,BRA,Latin America & Caribbean,Upper middle income,Brazilian Statistics Institute (IBGE) ; Source...,Brazil,NaN
28,BRB,Latin America & Caribbean,High income,Barbados Statistical Office ; Source of popula...,Barbados,NaN
29,BRN,East Asia & Pacific,High income,Economic Planning and Development - Prime Mini...,Brunei Darussalam,NaN
...,...,...,...,...,...,...
233,TLA,NaN,NaN,Latin America & the Caribbean (IDA & IBRD coun...,Latin America & Caribbean (IDA & IBRD),NaN
234,TLS,East Asia & Pacific,Lower middle income,Timor -Leste National Accounts from General di...,Timor-Leste,NaN
235,TMN,NaN,NaN,Middle East & North Africa (IDA & IBRD countri...,Middle East & North Africa (IDA & IBRD),NaN
236,TON,East Asia & Pacific,Upper middle income,Tonga Department of Statistics ; Source of pop...,Tonga,NaN
237,TSA,NaN,NaN,South Asia (IDA & IBRD countries) aggregate.,South Asia (IDA & IBRD),NaN
238,TSS,NaN,NaN,Sub-Saharan Africa (IDA & IBRD countries) aggr...,Sub-Saharan Africa (IDA & IBRD),NaN
239,TTO,Latin America & Caribbean,High income,Central Bank of Trinidad and Tobago ; Source o...,Trinidad and Tobago,NaN
240,TUN,Middle East & North Africa,Lower middle income,"National Bureau of Statistics, Central Bank, M...",Tunisia,NaN
241,TUR,Europe & Central Asia,Upper middle income,Turkish Statistical Institute ; Source of popu...,Turkey,NaN
242,TUV,East Asia & Pacific,Upper middle income,IMF Article IV and The US Graduate School (pit...,Tuvalu,NaN
243,TZA,Sub-Saharan Africa,Low income,Tanzania Bureau of Statistics ; Source of popu...,Tanzania,NaN
244,UGA,Sub-Saharan Africa,Low income,"Uganda Bureau of Statistics for SNA series , B...",Uganda,NaN
245,UKR,Europe & Central Asia,Lower middle income,State Statistics Committee of Ukraine ; Source...,Ukraine,NaN
246,UMC,NaN,NaN,Upper middle income group aggregate. Upper-mid...,Upper middle income,NaN
247,URY,Latin America & Caribbean,High income,Central Bank of Uruguay ; Source of population...,Uruguay,NaN
248,USA,North America,High income,OECD (Organization for Economic Cooperation an...,United States,NaN
249,UZB,Europe & Central Asia,Lower middle income,The State Committee of the Republic of Uzbekis...,Uzbekistan,NaN
250,VCT,Latin America & Caribbean,Upper middle income,Eastern Caribbean Central Bank ; Source of pop...,St. Vincent and the Grenadines,NaN
251,VEN,Latin America & Caribbean,Upper middle income,Central Bank of Venezuela ; Source of populati...,"Venezuela, RB",NaN
252,VGB,Latin America & Caribbean,High income,NaN,British Virgin Islands,NaN
253,VIR,Latin America & Caribbean,High income,Source of population estimates: U.S. Census Bu...,Virgin Islands (U.S.),NaN
254,VNM,East Asia & Pacific,Lower middle income,GSO (General Statistics Office of Vietnam) and...,Vietnam,NaN
255,VUT,East Asia & Pacific,Lower middle income,IMF Article IV ; Source of population estimat...,Vanuatu,NaN
256,WLD,NaN,NaN,World aggregate.,World,NaN
257,WSM,East Asia & Pacific,Upper middle income,IMF Article IV and Bank's country office ; Sou...,Samoa,NaN
258,XKX,Europe & Central Asia,Lower middle income,Kosovo Agency of Statistics ; Source of popula...,Kosovo,NaN
259,YEM,Middle East & North Africa,Low income,Figures are based on MFMmod data ; Source of ...,"Yemen, Rep.",NaN
260,ZAF,Sub-Saharan Africa,Upper middle income,(see also: https://www.imf.org/en/News/Article...,South Africa,NaN
261,ZMB,Sub-Saharan Africa,Lower middle income,"Central Statistics Office Zambia, Bank of Zamb...",Zambia,NaN
262,ZWE,Sub-Saharan Africa,Low income,Zimstat- Central Statistics Agency ; Source of...,Zimbabwe,NaN

In [14]:
df_4=pd.read_csv('F.csv')

In [15]:
df_4

,INDICATOR_CODE,INDICATOR_NAME,SOURCE_NOTE,SOURCE_ORGANIZATION,Unnamed: 4
0,SE.PRM.CMPT.FE.ZS,"Primary completion rate, female (% of relevant...","Primary completion rate, or gross intake ratio...",UNESCO Institute for Statistics (http://uis.un...,NaN

In [21]:
df_5=pd.read_excel('D.xls')

In [23]:
df_5

,Country Name,Country Code,1970,1971,1972,1973,1974,1975,1976,1977,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,94.007988,97.840759,NaN,NaN,101.255234,101.555870,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,NaN,NaN,NaN,NaN,4.401400,NaN,NaN,5.565010,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Angola,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,34.099152,33.640591,33.219440,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Albania,ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,91.322578,88.323898,93.626404,98.312523,88.298477,105.165398,102.982307,104.641220,104.833992,NaN
4,Andorra,AND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Arab World,ARB,37.921421,37.821861,37.587250,38.895599,40.319950,42.552952,44.158600,45.856030,...,79.891617,81.653358,82.704529,84.354813,82.289307,82.780792,82.489250,81.664879,81.857643,NaN
6,United Arab Emirates,ARE,NaN,NaN,NaN,NaN,32.605530,40.583801,44.558472,52.384380,...,NaN,NaN,NaN,94.604851,98.349442,102.991226,107.034660,NaN,NaN,NaN
7,Argentina,ARG,73.978813,74.693237,NaN,NaN,NaN,81.912910,81.672791,NaN,...,104.726601,104.316292,104.118797,102.791862,100.329308,101.206650,100.889343,102.769638,NaN,NaN
8,Armenia,ARM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,96.479362,95.532097,95.699883,NaN,96.500061,95.523361,91.295883,92.162277,NaN
9,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Antigua and Barbuda,ATG,NaN,NaN,NaN,NaN,NaN,79.190102,76.053223,NaN,...,88.344994,93.450287,87.338799,NaN,NaN,84.278961,74.703087,NaN,79.685608,NaN
11,Australia,AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Austria,AUT,NaN,95.713837,97.680527,97.935600,NaN,NaN,NaN,NaN,...,NaN,NaN,96.205032,97.154922,96.911179,98.807671,99.770363,99.599052,NaN,NaN
13,Azerbaijan,AZE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,91.428436,88.978851,92.183563,91.594589,86.546677,97.610519,101.618332,109.720207,107.618378,NaN
14,Burundi,BDI,NaN,3.018910,NaN,6.631340,7.342320,7.994380,7.794810,7.854950,...,46.606899,50.172871,56.233101,64.666702,74.729424,75.228127,70.664574,74.520287,74.870827,NaN
15,Belgium,BEL,NaN,NaN,NaN,NaN,69.204643,70.310402,71.265717,74.020821,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Benin,BEN,NaN,10.036290,11.963360,12.295490,11.367280,13.128270,14.386630,13.622220,...,NaN,58.195068,64.075813,65.538712,71.552170,73.551979,76.106850,76.031799,NaN,NaN
17,Burkina Faso,BFA,NaN,4.743380,4.602420,4.921830,5.016690,5.547910,5.447390,6.354600,...,40.446621,44.114422,NaN,56.032681,62.512409,62.712219,63.556900,64.067802,66.353790,NaN
18,Bangladesh,BGD,NaN,NaN,NaN,NaN,NaN,NaN,28.382959,NaN,...,66.323051,69.403389,NaN,NaN,NaN,NaN,NaN,NaN,122.972748,NaN
19,Bulgaria,BGR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,101.901657,113.772957,110.041054,101.386147,98.435303,98.122849,97.076447,94.330742,NaN,NaN
20,Bahrain,BHR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,91.950867,93.630821,93.002052,96.410057,100.321068,103.040100,100.677811,NaN
21,"Bahamas, The",BHS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,101.857689,94.785713,NaN,NaN,NaN,NaN,NaN,101.306122,NaN,NaN
22,Bosnia and Herzegovina,BIH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Belarus,BLR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,106.662369,103.096733,99.398483,98.293411,96.520401,98.094788,100.779449,NaN
24,Belize,BLZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,101.215973,98.275414,104.640907,109.002312,101.528664,100.712830,103.645699,105.953003,102.724869,NaN
25,Bermuda,BMU,NaN,NaN,NaN,NaN,NaN,74.826393,NaN,NaN,...,NaN,NaN,83.627197,78.391960,88.250000,NaN,NaN,NaN,NaN,NaN
26,Bolivia,BOL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,97.655273,98.782562,96.048637,92.155640,89.558372,90.624969,91.916786,NaN
27,Brazil,BRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Barbados,BRB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,97.686928,98.220062,99.087982,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Brunei Darussalam,BRN,NaN,NaN,104.753723,104.090660,111.666672,93.799683,106.666672,101.881989,...,101.898361,104.536140,110.088501,106.179443,105.587090,99.969872,103.003372,NaN,105.156952,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Latin America & the Caribbean (IDA & IBRD coun...,TLA,NaN,NaN,NaN,NaN,82.612831,82.985748,83.679031,85.317673,...,99.617958,99.490601,99.600227,100.477257,100.272491,100.525703,99.427490,99.087952,98.766220,NaN
235,Timor-Leste,TLS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,66.806847,67.609734,74.583603,83.086342,92.640350,98.118263,104.853561,97.601028,NaN,NaN
236,Middle East & North Africa (IDA & IBRD countries),TMN,34.259830,34.245060,34.542389,36.499111,38.574612,41.408520,43.482231,45.894852,...,86.329758,88.480377,89.459549,90.693718,87.692009,87.512192,86.883148,86.451042,86.732071,NaN
237,Tonga,TON,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79.985008,...,NaN,NaN,NaN,101.592621,106.462303,NaN,NaN,NaN,NaN,NaN
238,South Asia (IDA & IBRD),TSA,30.272680,30.433350,31.000620,31.354361,31.712761,32.810848,33.470501,34.170551,...,87.908089,87.732460,87.332352,90.898651,93.776588,95.324402,95.967323,95.264542,95.873138,NaN
239,Sub-Saharan Africa (IDA & IBRD countries),TSS,NaN,NaN,39.038540,39.587849,40.133541,40.955719,41.656830,42.828369,...,63.383041,63.873508,63.892620,65.282150,65.755798,66.205887,66.645721,66.713890,66.859077,NaN
240,Trinidad and Tobago,TTO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,95.839050,95.042679,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
241,Tunisia,TUN,NaN,NaN,NaN,42.511631,NaN,NaN,49.145149,52.289539,...,89.950180,98.843178,NaN,NaN,97.237633,100.230232,103.585747,NaN,NaN,NaN
242,Turkey,TUR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,97.614059,98.204597,100.956718,98.812088,NaN,90.898003,91.809753,NaN,NaN,NaN
243,Tuvalu,TUV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,108.510643,123.404259,98.947372,NaN,NaN
244,Tanzania,TZA,NaN,NaN,NaN,NaN,NaN,26.062820,28.385281,NaN,...,98.797821,88.595001,NaN,81.162613,75.769882,NaN,NaN,61.344959,NaN,NaN
245,Uganda,UGA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,72.463272,54.596840,52.267490,53.501301,53.565430,57.280029,NaN,53.492481,52.020809,NaN
246,Ukraine,UKR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,94.552391,96.077591,96.830452,98.419907,104.786240,104.376030,NaN,NaN,NaN,NaN
247,Upper middle income,UMC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.461502,100.540298,99.393867,98.777809,97.889702,94.305458,92.167343,93.822769,95.223419,NaN
248,Uruguay,URY,NaN,NaN,NaN,NaN,69.466240,NaN,68.947281,71.830750,...,106.381149,104.051437,NaN,NaN,102.263046,103.644112,102.557327,101.831444,NaN,NaN
249,United States,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
250,Uzbekistan,UZB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,91.466110,91.295670,91.508942,92.194283,95.469597,95.446854,97.289726,95.820267,97.022751,NaN
251,St. Vincent and the Grenadines,VCT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,91.586067,93.287270,97.852760,103.684212,98.812103,98.569862,97.898232,87.139687,NaN
252,"Venezuela, RB",VEN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,94.692558,93.351028,94.966438,96.353317,96.390572,96.705963,95.429718,92.364616,89.377876,NaN
253,British Virgin Islands,VGB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,Virgin Islands (U.S.),VIR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255,Vietnam,VNM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,99.165039,108.133041,103.771973,105.003029,NaN,NaN
256,Vanuatu,VUT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,87.074829,86.751984,NaN,NaN,97.764297,NaN,NaN,NaN,NaN,NaN
257,World,WLD,NaN,NaN,69.792778,70.243858,70.406609,70.909340,71.357132,72.189056,...,88.950577,89.197861,88.723602,90.016243,90.239838,89.686607,89.298782,89.337341,89.890083,NaN
258,Samoa,WSM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,101.292709,106.393738,106.880730,99.863197,NaN,98.051369,105.012962,103.518440,103.239197,NaN
259,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,"Yemen, Rep.",YEM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,54.093941,NaN,59.455952,60.745461,NaN,NaN,63.898941,NaN,NaN
261,South Africa,ZAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,82.650848,82.290802,NaN,NaN
262,Zambia,ZMB,NaN,NaN,50.408089,52.850182,56.292610,58.063820,58.726768,61.875832,...,78.407333,99.939362,NaN,86.377579,77.591408,NaN,NaN,NaN,NaN,NaN
263,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,89.227951,89.678162,NaN,NaN,NaN,NaN,NaN

In [24]:
df_6=pd.read_excel('GDP.xls')

In [25]:
df_6

,Country Name,Country Code,1961,1962,1963,1964,1965,1966,1967,1968,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-10.519748,-3.685030,3.446055,-1.369863,4.198232,0.848228,-0.450586,-0.211225,1.330511,NaN
1,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.390528,14.362441,0.426355,12.752287,5.600745,2.724543,1.451315,2.260314,2.665292,NaN
2,Angola,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.858713,4.859220,3.471981,8.542147,4.954590,4.822626,0.943576,-2.580097,-0.147207,NaN
3,Albania,ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.350000,3.710000,2.550000,1.420000,1.000000,1.770000,2.220000,3.350000,3.835544,NaN
4,Andorra,AND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-3.690654,-5.358826,-4.646543,-1.615218,0.351645,2.277683,0.842204,1.889124,1.873197,NaN
5,Arab World,ARB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.428014,4.772234,3.629151,6.658373,3.166753,2.456637,3.303769,3.239563,0.987176,NaN
6,United Arab Emirates,ARE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-5.242922,1.602810,6.930272,4.484626,5.053346,4.398697,5.064702,2.988442,0.790400,NaN
7,Argentina,ARG,5.427843,-0.852022,-5.308197,10.130298,10.569433,-0.659726,3.191997,4.822501,...,-5.918525,10.125398,6.003952,-1.026420,2.405324,-2.512615,2.731160,-1.822542,2.854466,NaN
8,Armenia,ARM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-14.149989,2.200000,4.700000,7.200000,3.300000,3.600000,3.200000,0.200000,7.500000,NaN
9,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-4.237288,0.442478,0.293686,-4.392387,-2.756508,0.944882,1.248050,-2.619414,-5.379747,NaN
10,Antigua and Barbuda,ATG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-12.107537,-7.200025,-2.079127,3.506610,-0.103866,4.658128,4.025739,5.589739,3.032606,NaN
11,Australia,AUS,2.485605,1.296478,6.214278,6.978724,5.983450,2.382491,6.302386,5.095868,...,1.922727,2.052942,2.451105,3.891940,2.639482,2.558338,2.351136,2.827311,1.957575,NaN
12,Austria,AUT,5.537979,2.648675,4.138268,6.124354,3.480175,5.642861,3.008048,4.472313,...,-3.764580,1.837095,2.922798,0.680444,0.025504,0.661275,1.142980,2.039575,2.550881,NaN
13,Azerbaijan,AZE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.410654,4.854339,0.065923,2.200000,5.796678,2.000000,1.100000,-3.100000,0.100000,NaN
14,Burundi,BDI,-13.746135,9.063158,4.135407,6.273038,3.967226,4.612993,13.821519,-0.297884,...,3.812747,5.124163,4.032602,4.446708,4.924195,4.240652,-3.900003,-0.600020,0.500010,NaN
15,Belgium,BEL,4.978423,5.212004,4.351584,6.956685,3.560660,3.155895,3.868147,4.194130,...,-2.253175,2.744213,1.798306,0.234779,0.200662,1.254677,1.716681,1.488680,1.692883,NaN
16,Benin,BEN,3.141280,-3.426410,4.730028,6.650759,5.293863,3.575863,1.078399,3.842336,...,2.329301,2.110199,2.962750,4.816478,7.189716,6.351832,2.095808,3.964860,5.837823,NaN
17,Burkina Faso,BFA,4.043928,6.128799,-1.268016,2.282819,3.764545,0.537613,8.823315,3.070774,...,2.962014,5.373373,6.626865,6.452699,5.792589,4.326837,3.894548,5.934135,6.302096,NaN
18,Bangladesh,BGD,6.058161,5.453031,-0.455894,10.952789,1.606258,2.566812,-1.875864,9.489454,...,5.045125,5.571802,6.464384,6.521435,6.013610,6.061059,6.552653,7.113489,7.284184,NaN
19,Bulgaria,BGR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-3.586146,1.324088,1.914906,0.030970,0.493921,1.837521,3.471186,3.936758,3.811248,NaN
20,Bahrain,BHR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.539772,4.334407,1.983823,3.732252,5.416504,4.349842,2.861968,3.470924,3.803522,NaN
21,"Bahamas, The",BHS,10.667097,10.451972,10.524055,10.501567,10.425596,9.071929,9.598114,8.421764,...,-4.175260,1.538777,0.612897,3.086687,-0.410429,-0.147989,1.044960,-1.689550,1.437191,NaN
22,Bosnia and Herzegovina,BIH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-3.002753,0.872151,0.958953,-0.821729,2.349396,1.149622,3.076823,3.144070,3.186203,NaN
23,Belarus,BLR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.199995,7.798267,5.378707,1.687136,1.003471,1.726385,-3.829571,-2.526446,2.421904,NaN
24,Belize,BLZ,4.892277,4.892652,4.956434,4.999880,4.930541,4.770845,4.913123,7.367225,...,0.670801,3.383472,2.162607,2.937813,0.851935,3.692371,3.431950,-0.588024,1.437289,NaN
25,Bermuda,BMU,4.680000,4.470000,1.070000,11.110000,4.760000,14.363636,13.275040,2.105263,...,-5.284177,-2.094114,-3.339494,-4.834540,-2.511154,NaN,NaN,NaN,NaN,NaN
26,Bolivia,BOL,2.089296,5.578918,6.797626,3.956597,4.913442,7.170590,6.317220,8.529443,...,3.357001,4.126723,5.204093,5.122275,6.796012,5.460570,4.857188,4.263919,4.195207,NaN
27,Brazil,BRA,10.275912,5.216059,0.874673,3.485582,3.053488,4.150360,4.915266,11.427282,...,-0.125812,7.528226,3.974423,1.921176,3.004823,0.503956,-3.545763,-3.305454,1.063861,NaN
28,Barbados,BRB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-3.972928,0.265446,0.657294,0.281154,0.009044,0.018086,0.904159,2.007168,1.000000,NaN
29,Brunei Darussalam,BRN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.764536,2.598966,3.745318,0.912842,-2.126029,-2.349747,-0.566815,-2.465515,1.328752,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Latin America & the Caribbean (IDA & IBRD coun...,TLA,6.530148,4.711969,2.454673,7.399589,5.100247,4.023309,4.340505,7.969808,...,-1.899517,6.043404,4.523104,2.849946,2.823864,1.049825,0.046384,-0.360044,1.785059,NaN
235,Timor-Leste,TLS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-6.055189,-1.171364,11.834426,4.962879,-11.001768,-26.048146,20.878436,0.827857,-8.002258,NaN
236,Middle East & North Africa (IDA & IBRD countries),TMN,NaN,NaN,NaN,NaN,NaN,7.368338,9.579483,11.965570,...,2.517372,5.253249,-1.020243,2.780376,1.659192,2.113558,0.959091,7.450696,3.017412,NaN
237,Tonga,TON,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.290613,3.585657,2.785146,0.890323,-3.120604,2.072607,3.711847,3.379474,2.700000,NaN
238,South Asia (IDA & IBRD),TSA,4.093377,3.301453,5.398704,7.683882,-1.058801,0.948368,6.463182,4.331383,...,7.133471,7.702667,5.137253,5.501737,6.087311,6.992302,7.480021,7.707317,6.932831,NaN
239,Sub-Saharan Africa (IDA & IBRD countries),TSS,1.449527,5.866192,6.342941,5.355114,4.956149,1.526042,-0.606544,3.009098,...,3.012665,5.582715,4.550758,4.534217,4.979826,4.679228,2.917077,1.214315,2.518456,NaN
240,Trinidad and Tobago,TTO,14.037071,2.742463,5.604597,7.630500,0.693850,4.056822,2.042514,5.215148,...,-4.390592,3.323331,-0.294354,1.293979,0.980850,-0.252163,1.517163,-5.957061,-2.336014,NaN
241,Tunisia,TUN,NaN,NaN,NaN,NaN,NaN,3.454868,0.161952,10.409729,...,3.043449,3.510609,-1.917178,3.997674,2.875524,2.971398,1.153616,1.108393,1.955126,NaN
242,Turkey,TUR,1.156069,5.571429,9.066306,5.459057,2.823530,11.212815,4.732510,6.777996,...,-4.704445,8.487358,11.113499,4.789920,8.491316,5.166672,6.085899,3.183819,7.441233,NaN
243,Tuvalu,TUV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-4.432851,-2.729428,7.515857,-3.835525,4.576642,1.347924,9.142912,3.034951,3.241589,NaN
244,Tanzania,TZA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.269105,6.336523,7.672155,4.500154,6.781586,6.732462,6.160629,6.867116,6.785680,NaN
245,Uganda,UGA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.801517,5.637600,9.391668,3.837456,3.586906,5.106307,5.187860,4.781000,3.863024,NaN
246,Ukraine,UKR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-14.758545,3.834388,5.465532,0.238681,-0.026730,-6.552619,-9.772974,2.440995,2.524513,NaN
247,Upper middle income,UMC,1.575834,4.486474,5.913202,8.224137,6.719493,6.202301,4.547909,7.643157,...,1.730857,7.465966,6.341957,5.254455,5.036413,4.212849,3.366850,3.935745,4.771082,NaN
248,Uruguay,URY,2.493038,-1.574549,0.170459,2.440521,1.045604,3.062856,-3.656834,1.888912,...,4.243494,7.803410,5.162133,3.538179,4.637539,3.238791,0.370741,1.689798,2.656684,NaN
249,United States,USA,2.300000,6.100000,4.400000,5.800000,6.400000,6.500000,2.500000,4.800000,...,-2.775530,2.721577,1.550836,2.249546,1.842081,2.451973,2.880910,1.567215,2.217010,NaN
250,Uzbekistan,UZB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.100000,8.500000,8.300000,8.200000,8.000000,7.792522,8.000000,7.800000,5.300000,NaN
251,St. Vincent and the Grenadines,VCT,4.527283,3.694262,-6.265339,3.669726,0.884935,0.000000,-9.523813,6.509706,...,-2.099061,-3.353526,-0.419351,1.382420,1.833169,1.213672,1.341639,1.975456,0.859946,NaN
252,"Venezuela, RB",VEN,3.192519,8.532934,3.900951,11.129345,4.162867,1.510250,2.833869,7.337233,...,-3.202303,-1.488791,4.176425,5.625957,1.343094,-3.894386,NaN,NaN,NaN,NaN
253,British Virgin Islands,VGB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,Virgin Islands (U.S.),VIR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-6.641493,0.904116,-8.158453,-15.019255,-5.830816,-0.962464,0.259151,0.936995,NaN,NaN
255,Vietnam,VNM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.397898,6.423238,6.240303,5.247367,5.421883,5.983655,6.679289,6.210812,6.812246,NaN
256,Vanuatu,VUT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.312816,1.629082,1.223226,1.754750,1.969146,2.331006,-0.801094,4.000574,4.500680,NaN
257,World,WLD,4.321343,5.563724,5.210133,6.665631,5.568284,5.797459,4.409756,6.191724,...,-1.740729,4.358058,3.151521,2.521433,2.653189,2.842105,2.860360,2.587991,3.153519,NaN
258,Samoa,WSM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-4.808272,0.479159,5.778544,0.402104,-1.933859,1.396756,1.451066,7.169420,2.704799,NaN
259,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.341666,3.309575,4.812563,2.895349,3.431230,1.198071,4.094455,4.056579,4.227909,NaN
260,"Yemen, Rep.",YEM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.866230,7.702307,-12.714897,2.392990,4.823519,-0.188690,-16.678463,-13.621458,-5.942320,NaN
261,South Africa,ZAF,3.844751,6.177883,7.373613,7.939782,6.122761,4.438308,7.196576,4.153445,...,-1.538089,3.039731,3.284168,2.213355,2.485201,1.846992,1.279549,0.565345,1.316745,NaN
262,Zambia,ZMB,1.361382,-2.490839,3.272393,12.214048,16.647456,-5.570310,7.919697,1.248330,...,9.220348,10.298206,5.564625,7.597617,5.059376,4.695826,2.919881,3.757178,3.403169,NaN
263,Zimbabwe,ZWE,6.316157,1.434471,6.244345,-1.106172,4.910571,1.523130,8.367009,1.970135,...,12.019561,19.675323,14.193913,16.665429,1.989493,2.376929,1.779873,0.755869,4.704035,NaN

In [26]:
df_7=pd.read_excel('H.xlsx')

In [27]:
df_7

,GOING PLACES,Unnamed: 1
0,Can a woman apply for a passport in the same w...,Yes = 1; No = 0
1,Can a woman legally travel outside the country...,Yes = 1; No = 0
2,Can a woman legally travel outside her home in...,Yes = 1; No = 0
3,Can a woman legally choose where to live in th...,Yes = 1; No = 0
4,STARTING A JOB,NaN
5,Can a woman get a job or pursue a trade or pro...,Yes = 1; No = 0
6,Does the law mandate nondiscrimination based o...,Yes = 1; No = 0
7,Is there legislation on sexual harassment in e...,Yes = 1; No = 0
8,Are there criminal penalties or civil remedies...,Yes = 1; No = 0
9,GETTING PAID,NaN
10,Does the law mandate equal remuneration for wo...,Yes = 1; No = 0
11,Can women work the same night hours as men?,Yes = 1; No = 0
12,"Can women work in jobs deemed hazardous, arduo...",Yes = 1; No = 0
13,Are women able to work in the same industries ...,Yes = 1; No = 0
14,GETTING MARRIED,NaN
15,Is a married woman not legally required to obe...,Yes = 1; No = 0
16,Can a woman be head of household or head of fa...,Yes = 1; No = 0; N/A (no head of household pro...
17,Is there domestic violence legislation?,Yes = 1; No = 0
18,Can a woman obtain a judgment of divorce in th...,Yes = 1; No = 0
19,Do women have the same rights to remarry as men?,Yes = 1; No = 0
20,HAVING CHILDREN,NaN
21,Is there paid leave of at least 14 weeks avail...,Yes = 1; No (no leave or leave<14 weeks)=0
22,Does the government pay 100% of maternity leav...,Yes=1; No=0
23,Is there paid paternity leave?,Yes=1; No=0
24,Is there paid parental leave?,Yes = 1; No = 0
25,Is dismissal of pregnant workers prohibited?,Yes = 1; No = 0
26,RUNNING A BUSINESS,NaN
27,Can a woman legally sign a contract in the sam...,Yes = 1; No = 0
28,Can a woman legally register a business in the...,Yes = 1; No = 0
29,Can a woman legally open a bank account in th...,Yes = 1; No = 0
30,Does the law prohibit discrimination by credit...,Yes = 1; No = 0
31,MANAGING ASSETS,NaN
32,Do men and married women have equal ownership ...,Yes = 1; No = 0
33,Do sons and daughters have equal rights to inh...,Yes = 1; No = 0
34,Do female and male surviving spouses have equa...,Yes = 1; No = 0\n
35,Does the law grant spouses equal administrativ...,Yes = 1; No = 0
36,Does the law provide for the valuation of nonm...,Yes = 1; No = 0
37,GETTING A PENSION,NaN
38,Are the ages at which men and women can retire...,Yes = 1; No (because \nwomen retire earlier) =...
39,Are the ages at which men and women can retire...,Yes = 1; No (because \nwomen retire earlier) =...
40,Is the mandatory retirement age for men and wo...,Yes = 1; No (because \nwomen retire earlier) =...
41,Does the law establish explicit pension care c...,Yes = 1; No (no credits) = 0; No (no national ...

In [4]:
df_8=pd.read_excel('W.xls')

In [5]:
df_8

,economy,wbcodev2,Region,Income group,reportyr,WBL INDEX,GOING PLACES,Can a woman apply for a passport in the same way as a man?,Can a woman legally travel outside the country in the same way as a man?,Can a woman legally travel outside her home in the same way as a man?,...,Do men and married women have equal ownership rights to property?,Do sons and daughters have equal rights to inherit assets from their parents?,Do female and male surviving spouses have equal rights to inherit assets?,Does the law grant spouses equal administrative authority over assets during marriage?,Does the law provide for the valuation of nonmonetary contributions?,GETTING A PENSION,Are the ages at which men and women can retire with full pension benefits equal?,Are the ages at which men and women can retire with partial pension benefits equal?,Is the mandatory retirement age for men and women equal?,Does the law establish explicit pension care credits for periods of childcare?
0,Afghanistan,AFG,South Asia,Low income,2009,28.75,25.0,No,Yes,No,...,Yes,No,No,Yes,No,25.0,No,No,Yes,No
1,Afghanistan,AFG,South Asia,Low income,2010,28.75,25.0,No,Yes,No,...,Yes,No,No,Yes,No,25.0,No,No,Yes,No
2,Afghanistan,AFG,South Asia,Low income,2011,28.75,25.0,No,Yes,No,...,Yes,No,No,Yes,No,25.0,No,No,Yes,No
3,Afghanistan,AFG,South Asia,Low income,2012,28.75,25.0,No,Yes,No,...,Yes,No,No,Yes,No,25.0,No,No,Yes,No
4,Afghanistan,AFG,South Asia,Low income,2013,28.75,25.0,No,Yes,No,...,Yes,No,No,Yes,No,25.0,No,No,Yes,No
5,Afghanistan,AFG,South Asia,Low income,2014,28.75,25.0,No,Yes,No,...,Yes,No,No,Yes,No,25.0,No,No,Yes,No
6,Afghanistan,AFG,South Asia,Low income,2015,28.75,25.0,No,Yes,No,...,Yes,No,No,Yes,No,25.0,No,No,Yes,No
7,Afghanistan,AFG,South Asia,Low income,2016,28.75,25.0,No,Yes,No,...,Yes,No,No,Yes,No,25.0,No,No,Yes,No
8,Afghanistan,AFG,South Asia,Low income,2017,38.13,50.0,Yes,Yes,No,...,Yes,No,No,Yes,No,25.0,No,No,Yes,No
9,Afghanistan,AFG,South Asia,Low income,2018,38.13,50.0,Yes,Yes,No,...,Yes,No,No,Yes,No,25.0,No,No,Yes,No
10,Albania,ALB,Europe & Central Asia,Upper middle income,2009,82.50,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes
11,Albania,ALB,Europe & Central Asia,Upper middle income,2010,82.50,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes
12,Albania,ALB,Europe & Central Asia,Upper middle income,2011,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes
13,Albania,ALB,Europe & Central Asia,Upper middle income,2012,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes
14,Albania,ALB,Europe & Central Asia,Upper middle income,2013,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes
15,Albania,ALB,Europe & Central Asia,Upper middle income,2014,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes
16,Albania,ALB,Europe & Central Asia,Upper middle income,2015,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes
17,Albania,ALB,Europe & Central Asia,Upper middle income,2016,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes
18,Albania,ALB,Europe & Central Asia,Upper middle income,2017,91.25,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes
19,Albania,ALB,Europe & Central Asia,Upper middle income,2018,91.25,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes
20,Algeria,DZA,Middle East & North Africa,Upper middle income,2009,55.00,75.0,No,Yes,Yes,...,Yes,No,No,Yes,No,25.0,No,No,No,Yes
21,Algeria,DZA,Middle East & North Africa,Upper middle income,2010,55.00,75.0,No,Yes,Yes,...,Yes,No,No,Yes,No,25.0,No,No,No,Yes
22,Algeria,DZA,Middle East & North Africa,Upper middle income,2011,55.00,75.0,No,Yes,Yes,...,Yes,No,No,Yes,No,25.0,No,No,No,Yes
23,Algeria,DZA,Middle East & North Africa,Upper middle income,2012,55.00,75.0,No,Yes,Yes,...,Yes,No,No,Yes,No,25.0,No,No,No,Yes
24,Algeria,DZA,Middle East & North Africa,Upper middle income,2013,55.00,75.0,No,Yes,Yes,...,Yes,No,No,Yes,No,25.0,No,No,No,Yes
25,Algeria,DZA,Middle East & North Africa,Upper middle income,2014,55.00,75.0,No,Yes,Yes,...,Yes,No,No,Yes,No,25.0,No,No,No,Yes
26,Algeria,DZA,Middle East & North Africa,Upper middle income,2015,55.00,75.0,No,Yes,Yes,...,Yes,No,No,Yes,No,25.0,No,No,No,Yes
27,Algeria,DZA,Middle East & North Africa,Upper middle income,2016,55.00,75.0,No,Yes,Yes,...,Yes,No,No,Yes,No,25.0,No,No,No,Yes
28,Algeria,DZA,Middle East & North Africa,Upper middle income,2017,57.50,75.0,No,Yes,Yes,...,Yes,No,No,Yes,No,25.0,No,No,No,Yes
29,Algeria,DZA,Middle East & North Africa,Upper middle income,2018,57.50,75.0,No,Yes,Yes,...,Yes,No,No,Yes,No,25.0,No,No,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1840,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2009,35.00,50.0,Yes,Yes,No,...,Yes,No,Yes,Yes,No,25.0,No,No,Yes,No
1841,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2010,35.00,50.0,Yes,Yes,No,...,Yes,No,Yes,Yes,No,25.0,No,No,Yes,No
1842,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2011,35.00,50.0,Yes,Yes,No,...,Yes,No,Yes,Yes,No,25.0,No,No,Yes,No
1843,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2012,35.00,50.0,Yes,Yes,No,...,Yes,No,Yes,Yes,No,25.0,No,No,Yes,No
1844,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2013,35.00,50.0,Yes,Yes,No,...,Yes,No,Yes,Yes,No,25.0,No,No,Yes,No
1845,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2014,35.00,50.0,Yes,Yes,No,...,Yes,No,Yes,Yes,No,25.0,No,No,Yes,No
1846,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2015,35.00,50.0,Yes,Yes,No,...,Yes,No,Yes,Yes,No,25.0,No,No,Yes,No
1847,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2016,35.00,50.0,Yes,Yes,No,...,Yes,No,Yes,Yes,No,25.0,No,No,Yes,No
1848,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2017,44.38,50.0,Yes,Yes,No,...,Yes,No,Yes,Yes,No,100.0,Yes,Yes,Yes,Yes
1849,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2018,46.88,50.0,Yes,Yes,No,...,Yes,No,Yes,Yes,No,100.0,Yes,Yes,Yes,Yes
1850,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2009,63.75,75.0,No,Yes,Yes,...,Yes,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No
1851,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2010,63.75,75.0,No,Yes,Yes,...,Yes,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No
1852,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2011,63.75,75.0,No,Yes,Yes,...,Yes,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No
1853,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2012,63.75,75.0,No,Yes,Yes,...,Yes,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No
1854,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2013,66.25,75.0,No,Yes,Yes,...,Yes,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No
1855,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2014,66.25,75.0,No,Yes,Yes,...,Yes,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No
1856,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2015,66.25,75.0,No,Yes,Yes,...,Yes,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No
1857,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2016,66.25,75.0,No,Yes,Yes,...,Yes,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No
1858,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2017,78.75,75.0,No,Yes,Yes,...,Yes,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No
1859,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2018,78.75,75.0,No,Yes,Yes,...,Yes,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No
1860,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2009,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes
1861,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2010,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes
1862,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2011,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes
1863,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2012,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes
1864,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2013,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes
1865,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2014,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes
1866,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2015,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes
1867,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2016,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes
1868,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2017,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes
1869,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2018,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes

In [8]:
df_8.columns = ['Country Name','Country Code','Region','Income Group','Year','WBL Index','Going Places','Passport','Travel Abroad','Travel','live liberty','Start job','Job freedom','Work Gender','work safty','pentalty','pay check','same pay','same hour','social expect','industry','Marriage','obey','head','legistration','judgement','remarry','Children','paid leave','leave benefit','paternity leave','parental leave','dismissal','business','legal contract','register business','bank account','prohibit discrimination','assets','equal ownership','inherit','surviving spouses','equal authority','nonmonetary contributions','GETTING A PENSION','full pension','partial pension','retirement age','childcare']

In [9]:
df_8

,Country Name,Country Code,Region,Income Group,Year,WBL Index,Going Places,Passport,Travel Abroad,Travel,...,equal ownership,inherit,surviving spouses,equal authority,nonmonetary contributions,GETTING A PENSION,full pension,partial pension,retirement age,childcare
0,Afghanistan,AFG,South Asia,Low income,2009,28.75,25.0,No,Yes,No,...,Yes,No,No,Yes,No,25.0,No,No,Yes,No
1,Afghanistan,AFG,South Asia,Low income,2010,28.75,25.0,No,Yes,No,...,Yes,No,No,Yes,No,25.0,No,No,Yes,No
2,Afghanistan,AFG,South Asia,Low income,2011,28.75,25.0,No,Yes,No,...,Yes,No,No,Yes,No,25.0,No,No,Yes,No
3,Afghanistan,AFG,South Asia,Low income,2012,28.75,25.0,No,Yes,No,...,Yes,No,No,Yes,No,25.0,No,No,Yes,No
4,Afghanistan,AFG,South Asia,Low income,2013,28.75,25.0,No,Yes,No,...,Yes,No,No,Yes,No,25.0,No,No,Yes,No
5,Afghanistan,AFG,South Asia,Low income,2014,28.75,25.0,No,Yes,No,...,Yes,No,No,Yes,No,25.0,No,No,Yes,No
6,Afghanistan,AFG,South Asia,Low income,2015,28.75,25.0,No,Yes,No,...,Yes,No,No,Yes,No,25.0,No,No,Yes,No
7,Afghanistan,AFG,South Asia,Low income,2016,28.75,25.0,No,Yes,No,...,Yes,No,No,Yes,No,25.0,No,No,Yes,No
8,Afghanistan,AFG,South Asia,Low income,2017,38.13,50.0,Yes,Yes,No,...,Yes,No,No,Yes,No,25.0,No,No,Yes,No
9,Afghanistan,AFG,South Asia,Low income,2018,38.13,50.0,Yes,Yes,No,...,Yes,No,No,Yes,No,25.0,No,No,Yes,No
10,Albania,ALB,Europe & Central Asia,Upper middle income,2009,82.50,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes
11,Albania,ALB,Europe & Central Asia,Upper middle income,2010,82.50,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes
12,Albania,ALB,Europe & Central Asia,Upper middle income,2011,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes
13,Albania,ALB,Europe & Central Asia,Upper middle income,2012,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes
14,Albania,ALB,Europe & Central Asia,Upper middle income,2013,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes
15,Albania,ALB,Europe & Central Asia,Upper middle income,2014,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes
16,Albania,ALB,Europe & Central Asia,Upper middle income,2015,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes
17,Albania,ALB,Europe & Central Asia,Upper middle income,2016,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes
18,Albania,ALB,Europe & Central Asia,Upper middle income,2017,91.25,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes
19,Albania,ALB,Europe & Central Asia,Upper middle income,2018,91.25,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes
20,Algeria,DZA,Middle East & North Africa,Upper middle income,2009,55.00,75.0,No,Yes,Yes,...,Yes,No,No,Yes,No,25.0,No,No,No,Yes
21,Algeria,DZA,Middle East & North Africa,Upper middle income,2010,55.00,75.0,No,Yes,Yes,...,Yes,No,No,Yes,No,25.0,No,No,No,Yes
22,Algeria,DZA,Middle East & North Africa,Upper middle income,2011,55.00,75.0,No,Yes,Yes,...,Yes,No,No,Yes,No,25.0,No,No,No,Yes
23,Algeria,DZA,Middle East & North Africa,Upper middle income,2012,55.00,75.0,No,Yes,Yes,...,Yes,No,No,Yes,No,25.0,No,No,No,Yes
24,Algeria,DZA,Middle East & North Africa,Upper middle income,2013,55.00,75.0,No,Yes,Yes,...,Yes,No,No,Yes,No,25.0,No,No,No,Yes
25,Algeria,DZA,Middle East & North Africa,Upper middle income,2014,55.00,75.0,No,Yes,Yes,...,Yes,No,No,Yes,No,25.0,No,No,No,Yes
26,Algeria,DZA,Middle East & North Africa,Upper middle income,2015,55.00,75.0,No,Yes,Yes,...,Yes,No,No,Yes,No,25.0,No,No,No,Yes
27,Algeria,DZA,Middle East & North Africa,Upper middle income,2016,55.00,75.0,No,Yes,Yes,...,Yes,No,No,Yes,No,25.0,No,No,No,Yes
28,Algeria,DZA,Middle East & North Africa,Upper middle income,2017,57.50,75.0,No,Yes,Yes,...,Yes,No,No,Yes,No,25.0,No,No,No,Yes
29,Algeria,DZA,Middle East & North Africa,Upper middle income,2018,57.50,75.0,No,Yes,Yes,...,Yes,No,No,Yes,No,25.0,No,No,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1840,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2009,35.00,50.0,Yes,Yes,No,...,Yes,No,Yes,Yes,No,25.0,No,No,Yes,No
1841,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2010,35.00,50.0,Yes,Yes,No,...,Yes,No,Yes,Yes,No,25.0,No,No,Yes,No
1842,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2011,35.00,50.0,Yes,Yes,No,...,Yes,No,Yes,Yes,No,25.0,No,No,Yes,No
1843,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2012,35.00,50.0,Yes,Yes,No,...,Yes,No,Yes,Yes,No,25.0,No,No,Yes,No
1844,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2013,35.00,50.0,Yes,Yes,No,...,Yes,No,Yes,Yes,No,25.0,No,No,Yes,No
1845,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2014,35.00,50.0,Yes,Yes,No,...,Yes,No,Yes,Yes,No,25.0,No,No,Yes,No
1846,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2015,35.00,50.0,Yes,Yes,No,...,Yes,No,Yes,Yes,No,25.0,No,No,Yes,No
1847,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2016,35.00,50.0,Yes,Yes,No,...,Yes,No,Yes,Yes,No,25.0,No,No,Yes,No
1848,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2017,44.38,50.0,Yes,Yes,No,...,Yes,No,Yes,Yes,No,100.0,Yes,Yes,Yes,Yes
1849,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2018,46.88,50.0,Yes,Yes,No,...,Yes,No,Yes,Yes,No,100.0,Yes,Yes,Yes,Yes
1850,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2009,63.75,75.0,No,Yes,Yes,...,Yes,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No
1851,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2010,63.75,75.0,No,Yes,Yes,...,Yes,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No
1852,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2011,63.75,75.0,No,Yes,Yes,...,Yes,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No
1853,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2012,63.75,75.0,No,Yes,Yes,...,Yes,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No
1854,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2013,66.25,75.0,No,Yes,Yes,...,Yes,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No
1855,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2014,66.25,75.0,No,Yes,Yes,...,Yes,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No
1856,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2015,66.25,75.0,No,Yes,Yes,...,Yes,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No
1857,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2016,66.25,75.0,No,Yes,Yes,...,Yes,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No
1858,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2017,78.75,75.0,No,Yes,Yes,...,Yes,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No
1859,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2018,78.75,75.0,No,Yes,Yes,...,Yes,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No
1860,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2009,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes
1861,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2010,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes
1862,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2011,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes
1863,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2012,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes
1864,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2013,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes
1865,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2014,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes
1866,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2015,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes
1867,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2016,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes
1868,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2017,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes
1869,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2018,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes

In [107]:
df_9=pd.read_excel('GDP2.xls')

In [108]:
df_9

,Country Name,Country Code,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Aruba,ABW,-10.519748,-3.685030,3.446055,-1.369863,4.198232,0.848228,-0.450586,-0.211225,1.330511
1,Afghanistan,AFG,21.390528,14.362441,0.426355,12.752287,5.600745,2.724543,1.451315,2.260314,2.665292
2,Angola,AGO,0.858713,4.859220,3.471981,8.542147,4.954590,4.822626,0.943576,-2.580097,-0.147207
3,Albania,ALB,3.350000,3.710000,2.550000,1.420000,1.000000,1.770000,2.220000,3.350000,3.835544
4,Andorra,AND,-3.690654,-5.358826,-4.646543,-1.615218,0.351645,2.277683,0.842204,1.889124,1.873197
5,Arab World,ARB,0.428014,4.772234,3.629151,6.658373,3.166753,2.456637,3.303769,3.239563,0.987176
6,United Arab Emirates,ARE,-5.242922,1.602810,6.930272,4.484626,5.053346,4.398697,5.064702,2.988442,0.790400
7,Argentina,ARG,-5.918525,10.125398,6.003952,-1.026420,2.405324,-2.512615,2.731160,-1.822542,2.854466
8,Armenia,ARM,-14.149989,2.200000,4.700000,7.200000,3.300000,3.600000,3.200000,0.200000,7.500000
9,American Samoa,ASM,-4.237288,0.442478,0.293686,-4.392387,-2.756508,0.944882,1.248050,-2.619414,-5.379747
10,Antigua and Barbuda,ATG,-12.107537,-7.200025,-2.079127,3.506610,-0.103866,4.658128,4.025739,5.589739,3.032606
11,Australia,AUS,1.922727,2.052942,2.451105,3.891940,2.639482,2.558338,2.351136,2.827311,1.957575
12,Austria,AUT,-3.764580,1.837095,2.922798,0.680444,0.025504,0.661275,1.142980,2.039575,2.550881
13,Azerbaijan,AZE,9.410654,4.854339,0.065923,2.200000,5.796678,2.000000,1.100000,-3.100000,0.100000
14,Burundi,BDI,3.812747,5.124163,4.032602,4.446708,4.924195,4.240652,-3.900003,-0.600020,0.500010
15,Belgium,BEL,-2.253175,2.744213,1.798306,0.234779,0.200662,1.254677,1.716681,1.488680,1.692883
16,Benin,BEN,2.329301,2.110199,2.962750,4.816478,7.189716,6.351832,2.095808,3.964860,5.837823
17,Burkina Faso,BFA,2.962014,5.373373,6.626865,6.452699,5.792589,4.326837,3.894548,5.934135,6.302096
18,Bangladesh,BGD,5.045125,5.571802,6.464384,6.521435,6.013610,6.061059,6.552653,7.113489,7.284184
19,Bulgaria,BGR,-3.586146,1.324088,1.914906,0.030970,0.493921,1.837521,3.471186,3.936758,3.811248
20,Bahrain,BHR,2.539772,4.334407,1.983823,3.732252,5.416504,4.349842,2.861968,3.470924,3.803522
21,"Bahamas, The",BHS,-4.175260,1.538777,0.612897,3.086687,-0.410429,-0.147989,1.044960,-1.689550,1.437191
22,Bosnia and Herzegovina,BIH,-3.002753,0.872151,0.958953,-0.821729,2.349396,1.149622,3.076823,3.144070,3.186203
23,Belarus,BLR,0.199995,7.798267,5.378707,1.687136,1.003471,1.726385,-3.829571,-2.526446,2.421904
24,Belize,BLZ,0.670801,3.383472,2.162607,2.937813,0.851935,3.692371,3.431950,-0.588024,1.437289
25,Bermuda,BMU,-5.284177,-2.094114,-3.339494,-4.834540,-2.511154,NaN,NaN,NaN,NaN
26,Bolivia,BOL,3.357001,4.126723,5.204093,5.122275,6.796012,5.460570,4.857188,4.263919,4.195207
27,Brazil,BRA,-0.125812,7.528226,3.974423,1.921176,3.004823,0.503956,-3.545763,-3.305454,1.063861
28,Barbados,BRB,-3.972928,0.265446,0.657294,0.281154,0.009044,0.018086,0.904159,2.007168,1.000000
29,Brunei Darussalam,BRN,-1.764536,2.598966,3.745318,0.912842,-2.126029,-2.349747,-0.566815,-2.465515,1.328752
...,...,...,...,...,...,...,...,...,...,...,...
234,Latin America & the Caribbean (IDA & IBRD coun...,TLA,-1.899517,6.043404,4.523104,2.849946,2.823864,1.049825,0.046384,-0.360044,1.785059
235,Timor-Leste,TLS,-6.055189,-1.171364,11.834426,4.962879,-11.001768,-26.048146,20.878436,0.827857,-8.002258
236,Middle East & North Africa (IDA & IBRD countries),TMN,2.517372,5.253249,-1.020243,2.780376,1.659192,2.113558,0.959091,7.450696,3.017412
237,Tonga,TON,2.290613,3.585657,2.785146,0.890323,-3.120604,2.072607,3.711847,3.379474,2.700000
238,South Asia (IDA & IBRD),TSA,7.133471,7.702667,5.137253,5.501737,6.087311,6.992302,7.480021,7.707317,6.932831
239,Sub-Saharan Africa (IDA & IBRD countries),TSS,3.012665,5.582715,4.550758,4.534217,4.979826,4.679228,2.917077,1.214315,2.518456
240,Trinidad and Tobago,TTO,-4.390592,3.323331,-0.294354,1.293979,0.980850,-0.252163,1.517163,-5.957061,-2.336014
241,Tunisia,TUN,3.043449,3.510609,-1.917178,3.997674,2.875524,2.971398,1.153616,1.108393,1.955126
242,Turkey,TUR,-4.704445,8.487358,11.113499,4.789920,8.491316,5.166672,6.085899,3.183819,7.441233
243,Tuvalu,TUV,-4.432851,-2.729428,7.515857,-3.835525,4.576642,1.347924,9.142912,3.034951,3.241589
244,Tanzania,TZA,5.269105,6.336523,7.672155,4.500154,6.781586,6.732462,6.160629,6.867116,6.785680
245,Uganda,UGA,6.801517,5.637600,9.391668,3.837456,3.586906,5.106307,5.187860,4.781000,3.863024
246,Ukraine,UKR,-14.758545,3.834388,5.465532,0.238681,-0.026730,-6.552619,-9.772974,2.440995,2.524513
247,Upper middle income,UMC,1.730857,7.465966,6.341957,5.254455,5.036413,4.212849,3.366850,3.935745,4.771082
248,Uruguay,URY,4.243494,7.803410,5.162133,3.538179,4.637539,3.238791,0.370741,1.689798,2.656684
249,United States,USA,-2.775530,2.721577,1.550836,2.249546,1.842081,2.451973,2.880910,1.567215,2.217010
250,Uzbekistan,UZB,8.100000,8.500000,8.300000,8.200000,8.000000,7.792522,8.000000,7.800000,5.300000
251,St. Vincent and the Grenadines,VCT,-2.099061,-3.353526,-0.419351,1.382420,1.833169,1.213672,1.341639,1.975456,0.859946
252,"Venezuela, RB",VEN,-3.202303,-1.488791,4.176425,5.625957,1.343094,-3.894386,NaN,NaN,NaN
253,British Virgin Islands,VGB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,Virgin Islands (U.S.),VIR,-6.641493,0.904116,-8.158453,-15.019255,-5.830816,-0.962464,0.259151,0.936995,NaN
255,Vietnam,VNM,5.397898,6.423238,6.240303,5.247367,5.421883,5.983655,6.679289,6.210812,6.812246
256,Vanuatu,VUT,3.312816,1.629082,1.223226,1.754750,1.969146,2.331006,-0.801094,4.000574,4.500680
257,World,WLD,-1.740729,4.358058,3.151521,2.521433,2.653189,2.842105,2.860360,2.587991,3.153519
258,Samoa,WSM,-4.808272,0.479159,5.778544,0.402104,-1.933859,1.396756,1.451066,7.169420,2.704799
259,Kosovo,XKX,3.341666,3.309575,4.812563,2.895349,3.431230,1.198071,4.094455,4.056579,4.227909
260,"Yemen, Rep.",YEM,3.866230,7.702307,-12.714897,2.392990,4.823519,-0.188690,-16.678463,-13.621458,-5.942320
261,South Africa,ZAF,-1.538089,3.039731,3.284168,2.213355,2.485201,1.846992,1.279549,0.565345,1.316745
262,Zambia,ZMB,9.220348,10.298206,5.564625,7.597617,5.059376,4.695826,2.919881,3.757178,3.403169
263,Zimbabwe,ZWE,12.019561,19.675323,14.193913,16.665429,1.989493,2.376929,1.779873,0.755869,4.704035

In [118]:
df_GDP=pd.melt(df_9,id_vars=['Country Name','Country Code'], var_name=
               [ 'Year'],value_name='GDP')

In [119]:
df_GDP

,Country Name,Country Code,Year,GDP
0,Aruba,ABW,2009,-10.519748
1,Afghanistan,AFG,2009,21.390528
2,Angola,AGO,2009,0.858713
3,Albania,ALB,2009,3.350000
4,Andorra,AND,2009,-3.690654
5,Arab World,ARB,2009,0.428014
6,United Arab Emirates,ARE,2009,-5.242922
7,Argentina,ARG,2009,-5.918525
8,Armenia,ARM,2009,-14.149989
9,American Samoa,ASM,2009,-4.237288
10,Antigua and Barbuda,ATG,2009,-12.107537
11,Australia,AUS,2009,1.922727
12,Austria,AUT,2009,-3.764580
13,Azerbaijan,AZE,2009,9.410654
14,Burundi,BDI,2009,3.812747
15,Belgium,BEL,2009,-2.253175
16,Benin,BEN,2009,2.329301
17,Burkina Faso,BFA,2009,2.962014
18,Bangladesh,BGD,2009,5.045125
19,Bulgaria,BGR,2009,-3.586146
20,Bahrain,BHR,2009,2.539772
21,"Bahamas, The",BHS,2009,-4.175260
22,Bosnia and Herzegovina,BIH,2009,-3.002753
23,Belarus,BLR,2009,0.199995
24,Belize,BLZ,2009,0.670801
25,Bermuda,BMU,2009,-5.284177
26,Bolivia,BOL,2009,3.357001
27,Brazil,BRA,2009,-0.125812
28,Barbados,BRB,2009,-3.972928
29,Brunei Darussalam,BRN,2009,-1.764536
...,...,...,...,...
2346,Latin America & the Caribbean (IDA & IBRD coun...,TLA,2017,1.785059
2347,Timor-Leste,TLS,2017,-8.002258
2348,Middle East & North Africa (IDA & IBRD countries),TMN,2017,3.017412
2349,Tonga,TON,2017,2.700000
2350,South Asia (IDA & IBRD),TSA,2017,6.932831
2351,Sub-Saharan Africa (IDA & IBRD countries),TSS,2017,2.518456
2352,Trinidad and Tobago,TTO,2017,-2.336014
2353,Tunisia,TUN,2017,1.955126
2354,Turkey,TUR,2017,7.441233
2355,Tuvalu,TUV,2017,3.241589
2356,Tanzania,TZA,2017,6.785680
2357,Uganda,UGA,2017,3.863024
2358,Ukraine,UKR,2017,2.524513
2359,Upper middle income,UMC,2017,4.771082
2360,Uruguay,URY,2017,2.656684
2361,United States,USA,2017,2.217010
2362,Uzbekistan,UZB,2017,5.300000
2363,St. Vincent and the Grenadines,VCT,2017,0.859946
2364,"Venezuela, RB",VEN,2017,NaN
2365,British Virgin Islands,VGB,2017,NaN
2366,Virgin Islands (U.S.),VIR,2017,NaN
2367,Vietnam,VNM,2017,6.812246
2368,Vanuatu,VUT,2017,4.500680
2369,World,WLD,2017,3.153519
2370,Samoa,WSM,2017,2.704799
2371,Kosovo,XKX,2017,4.227909
2372,"Yemen, Rep.",YEM,2017,-5.942320
2373,South Africa,ZAF,2017,1.316745
2374,Zambia,ZMB,2017,3.403169
2375,Zimbabwe,ZWE,2017,4.704035

In [120]:
df_10 = pd.merge(df_8, df_GDP, on=['Country Name','Country Code','Year'])

In [121]:
df_10

,Country Name,Country Code,Region,Income Group,Year,WBL Index,Going Places,Passport,Travel Abroad,Travel,...,inherit,surviving spouses,equal authority,nonmonetary contributions,GETTING A PENSION,full pension,partial pension,retirement age,childcare,GDP
0,Afghanistan,AFG,South Asia,Low income,2009,28.75,25.0,No,Yes,No,...,No,No,Yes,No,25.0,No,No,Yes,No,21.390528
1,Afghanistan,AFG,South Asia,Low income,2010,28.75,25.0,No,Yes,No,...,No,No,Yes,No,25.0,No,No,Yes,No,14.362441
2,Afghanistan,AFG,South Asia,Low income,2011,28.75,25.0,No,Yes,No,...,No,No,Yes,No,25.0,No,No,Yes,No,0.426355
3,Afghanistan,AFG,South Asia,Low income,2012,28.75,25.0,No,Yes,No,...,No,No,Yes,No,25.0,No,No,Yes,No,12.752287
4,Afghanistan,AFG,South Asia,Low income,2013,28.75,25.0,No,Yes,No,...,No,No,Yes,No,25.0,No,No,Yes,No,5.600745
5,Afghanistan,AFG,South Asia,Low income,2014,28.75,25.0,No,Yes,No,...,No,No,Yes,No,25.0,No,No,Yes,No,2.724543
6,Afghanistan,AFG,South Asia,Low income,2015,28.75,25.0,No,Yes,No,...,No,No,Yes,No,25.0,No,No,Yes,No,1.451315
7,Afghanistan,AFG,South Asia,Low income,2016,28.75,25.0,No,Yes,No,...,No,No,Yes,No,25.0,No,No,Yes,No,2.260314
8,Afghanistan,AFG,South Asia,Low income,2017,38.13,50.0,Yes,Yes,No,...,No,No,Yes,No,25.0,No,No,Yes,No,2.665292
9,Albania,ALB,Europe & Central Asia,Upper middle income,2009,82.50,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes,3.350000
10,Albania,ALB,Europe & Central Asia,Upper middle income,2010,82.50,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes,3.710000
11,Albania,ALB,Europe & Central Asia,Upper middle income,2011,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes,2.550000
12,Albania,ALB,Europe & Central Asia,Upper middle income,2012,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes,1.420000
13,Albania,ALB,Europe & Central Asia,Upper middle income,2013,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes,1.000000
14,Albania,ALB,Europe & Central Asia,Upper middle income,2014,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes,1.770000
15,Albania,ALB,Europe & Central Asia,Upper middle income,2015,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes,2.220000
16,Albania,ALB,Europe & Central Asia,Upper middle income,2016,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes,3.350000
17,Albania,ALB,Europe & Central Asia,Upper middle income,2017,91.25,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,50.0,No,No,Yes,Yes,3.835544
18,Algeria,DZA,Middle East & North Africa,Upper middle income,2009,55.00,75.0,No,Yes,Yes,...,No,No,Yes,No,25.0,No,No,No,Yes,1.632244
19,Algeria,DZA,Middle East & North Africa,Upper middle income,2010,55.00,75.0,No,Yes,Yes,...,No,No,Yes,No,25.0,No,No,No,Yes,3.634145
20,Algeria,DZA,Middle East & North Africa,Upper middle income,2011,55.00,75.0,No,Yes,Yes,...,No,No,Yes,No,25.0,No,No,No,Yes,2.891866
21,Algeria,DZA,Middle East & North Africa,Upper middle income,2012,55.00,75.0,No,Yes,Yes,...,No,No,Yes,No,25.0,No,No,No,Yes,3.374769
22,Algeria,DZA,Middle East & North Africa,Upper middle income,2013,55.00,75.0,No,Yes,Yes,...,No,No,Yes,No,25.0,No,No,No,Yes,2.767639
23,Algeria,DZA,Middle East & North Africa,Upper middle income,2014,55.00,75.0,No,Yes,Yes,...,No,No,Yes,No,25.0,No,No,No,Yes,3.789121
24,Algeria,DZA,Middle East & North Africa,Upper middle income,2015,55.00,75.0,No,Yes,Yes,...,No,No,Yes,No,25.0,No,No,No,Yes,3.763467
25,Algeria,DZA,Middle East & North Africa,Upper middle income,2016,55.00,75.0,No,Yes,Yes,...,No,No,Yes,No,25.0,No,No,No,Yes,3.300000
26,Algeria,DZA,Middle East & North Africa,Upper middle income,2017,57.50,75.0,No,Yes,Yes,...,No,No,Yes,No,25.0,No,No,No,Yes,1.600000
27,Angola,AGO,Sub-Saharan Africa,Lower middle income,2009,65.00,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,25.0,No,No,Yes,No,0.858713
28,Angola,AGO,Sub-Saharan Africa,Lower middle income,2010,71.25,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,75.0,Yes,Yes,Yes,No,4.859220
29,Angola,AGO,Sub-Saharan Africa,Lower middle income,2011,71.25,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,75.0,Yes,Yes,Yes,No,3.471981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1599,Vietnam,VNM,East Asia & Pacific,Lower middle income,2015,79.38,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,25.0,No,Yes,No,No,6.679289
1600,Vietnam,VNM,East Asia & Pacific,Lower middle income,2016,79.38,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,25.0,No,Yes,No,No,6.210812
1601,Vietnam,VNM,East Asia & Pacific,Lower middle income,2017,81.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,25.0,No,Yes,No,No,6.812246
1602,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2009,35.00,50.0,Yes,Yes,No,...,No,Yes,Yes,No,25.0,No,No,Yes,No,8.662535
1603,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2010,35.00,50.0,Yes,Yes,No,...,No,Yes,Yes,No,25.0,No,No,Yes,No,8.099089
1604,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2011,35.00,50.0,Yes,Yes,No,...,No,Yes,Yes,No,25.0,No,No,Yes,No,12.413635
1605,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2012,35.00,50.0,Yes,Yes,No,...,No,Yes,Yes,No,25.0,No,No,Yes,No,6.284236
1606,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2013,35.00,50.0,Yes,Yes,No,...,No,Yes,Yes,No,25.0,No,No,Yes,No,2.217422
1607,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2014,35.00,50.0,Yes,Yes,No,...,No,Yes,Yes,No,25.0,No,No,Yes,No,-0.181891
1608,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2015,35.00,50.0,Yes,Yes,No,...,No,Yes,Yes,No,25.0,No,No,Yes,No,3.428732
1609,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2016,35.00,50.0,Yes,Yes,No,...,No,Yes,Yes,No,25.0,No,No,Yes,No,4.708435
1610,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2017,44.38,50.0,Yes,Yes,No,...,No,Yes,Yes,No,100.0,Yes,Yes,Yes,Yes,3.140237
1611,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2009,63.75,75.0,No,Yes,Yes,...,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No,9.220348
1612,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2010,63.75,75.0,No,Yes,Yes,...,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No,10.298206
1613,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2011,63.75,75.0,No,Yes,Yes,...,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No,5.564625
1614,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2012,63.75,75.0,No,Yes,Yes,...,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No,7.597617
1615,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2013,66.25,75.0,No,Yes,Yes,...,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No,5.059376
1616,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2014,66.25,75.0,No,Yes,Yes,...,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No,4.695826
1617,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2015,66.25,75.0,No,Yes,Yes,...,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No,2.919881
1618,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2016,66.25,75.0,No,Yes,Yes,...,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No,3.757178
1619,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2017,78.75,75.0,No,Yes,Yes,...,Yes,Yes,Yes,No,75.0,Yes,Yes,Yes,No,3.403169
1620,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2009,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes,12.019561
1621,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2010,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes,19.675323
1622,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2011,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes,14.193913
1623,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2012,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes,16.665429
1624,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2013,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes,1.989493
1625,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2014,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes,2.376929
1626,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2015,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes,1.779873
1627,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2016,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes,0.755869
1628,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2017,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes,4.704035

In [122]:
df_10.to_csv("GDP.csv")

In [123]:
df_11=pd.read_excel('D1.xls')

In [124]:
df_Lit=pd.melt(df_11,id_vars=['Country Name','Country Code'], var_name=
               [ 'Year'],value_name='Literacy')

In [126]:
df_Lit

,Country Name,Country Code,Year,Literacy
0,Aruba,ABW,2009,94.007988
1,Afghanistan,AFG,2009,NaN
2,Angola,AGO,2009,34.099152
3,Albania,ALB,2009,91.322578
4,Andorra,AND,2009,NaN
5,Arab World,ARB,2009,79.891617
6,United Arab Emirates,ARE,2009,NaN
7,Argentina,ARG,2009,104.726601
8,Armenia,ARM,2009,NaN
9,American Samoa,ASM,2009,NaN
10,Antigua and Barbuda,ATG,2009,88.344994
11,Australia,AUS,2009,NaN
12,Austria,AUT,2009,NaN
13,Azerbaijan,AZE,2009,91.428436
14,Burundi,BDI,2009,46.606899
15,Belgium,BEL,2009,NaN
16,Benin,BEN,2009,NaN
17,Burkina Faso,BFA,2009,40.446621
18,Bangladesh,BGD,2009,66.323051
19,Bulgaria,BGR,2009,101.901657
20,Bahrain,BHR,2009,NaN
21,"Bahamas, The",BHS,2009,101.857689
22,Bosnia and Herzegovina,BIH,2009,NaN
23,Belarus,BLR,2009,NaN
24,Belize,BLZ,2009,101.215973
25,Bermuda,BMU,2009,NaN
26,Bolivia,BOL,2009,NaN
27,Brazil,BRA,2009,NaN
28,Barbados,BRB,2009,97.686928
29,Brunei Darussalam,BRN,2009,101.898361
...,...,...,...,...
2346,Latin America & the Caribbean (IDA & IBRD coun...,TLA,2017,98.766220
2347,Timor-Leste,TLS,2017,NaN
2348,Middle East & North Africa (IDA & IBRD countries),TMN,2017,86.732071
2349,Tonga,TON,2017,NaN
2350,South Asia (IDA & IBRD),TSA,2017,95.873138
2351,Sub-Saharan Africa (IDA & IBRD countries),TSS,2017,66.859077
2352,Trinidad and Tobago,TTO,2017,NaN
2353,Tunisia,TUN,2017,NaN
2354,Turkey,TUR,2017,NaN
2355,Tuvalu,TUV,2017,NaN
2356,Tanzania,TZA,2017,NaN
2357,Uganda,UGA,2017,52.020809
2358,Ukraine,UKR,2017,NaN
2359,Upper middle income,UMC,2017,95.223419
2360,Uruguay,URY,2017,NaN
2361,United States,USA,2017,NaN
2362,Uzbekistan,UZB,2017,97.022751
2363,St. Vincent and the Grenadines,VCT,2017,87.139687
2364,"Venezuela, RB",VEN,2017,89.377876
2365,British Virgin Islands,VGB,2017,NaN
2366,Virgin Islands (U.S.),VIR,2017,NaN
2367,Vietnam,VNM,2017,NaN
2368,Vanuatu,VUT,2017,NaN
2369,World,WLD,2017,89.890083
2370,Samoa,WSM,2017,103.239197
2371,Kosovo,XKX,2017,NaN
2372,"Yemen, Rep.",YEM,2017,NaN
2373,South Africa,ZAF,2017,NaN
2374,Zambia,ZMB,2017,NaN
2375,Zimbabwe,ZWE,2017,NaN

In [127]:
df_all = pd.merge(df_10, df_Lit, on=['Country Name','Country Code','Year'])

In [128]:
df_all

,Country Name,Country Code,Region,Income Group,Year,WBL Index,Going Places,Passport,Travel Abroad,Travel,...,surviving spouses,equal authority,nonmonetary contributions,GETTING A PENSION,full pension,partial pension,retirement age,childcare,GDP,Literacy
0,Afghanistan,AFG,South Asia,Low income,2009,28.75,25.0,No,Yes,No,...,No,Yes,No,25.0,No,No,Yes,No,21.390528,NaN
1,Afghanistan,AFG,South Asia,Low income,2010,28.75,25.0,No,Yes,No,...,No,Yes,No,25.0,No,No,Yes,No,14.362441,NaN
2,Afghanistan,AFG,South Asia,Low income,2011,28.75,25.0,No,Yes,No,...,No,Yes,No,25.0,No,No,Yes,No,0.426355,NaN
3,Afghanistan,AFG,South Asia,Low income,2012,28.75,25.0,No,Yes,No,...,No,Yes,No,25.0,No,No,Yes,No,12.752287,NaN
4,Afghanistan,AFG,South Asia,Low income,2013,28.75,25.0,No,Yes,No,...,No,Yes,No,25.0,No,No,Yes,No,5.600745,NaN
5,Afghanistan,AFG,South Asia,Low income,2014,28.75,25.0,No,Yes,No,...,No,Yes,No,25.0,No,No,Yes,No,2.724543,NaN
6,Afghanistan,AFG,South Asia,Low income,2015,28.75,25.0,No,Yes,No,...,No,Yes,No,25.0,No,No,Yes,No,1.451315,NaN
7,Afghanistan,AFG,South Asia,Low income,2016,28.75,25.0,No,Yes,No,...,No,Yes,No,25.0,No,No,Yes,No,2.260314,NaN
8,Afghanistan,AFG,South Asia,Low income,2017,38.13,50.0,Yes,Yes,No,...,No,Yes,No,25.0,No,No,Yes,No,2.665292,NaN
9,Albania,ALB,Europe & Central Asia,Upper middle income,2009,82.50,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,50.0,No,No,Yes,Yes,3.350000,91.322578
10,Albania,ALB,Europe & Central Asia,Upper middle income,2010,82.50,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,50.0,No,No,Yes,Yes,3.710000,88.323898
11,Albania,ALB,Europe & Central Asia,Upper middle income,2011,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,50.0,No,No,Yes,Yes,2.550000,93.626404
12,Albania,ALB,Europe & Central Asia,Upper middle income,2012,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,50.0,No,No,Yes,Yes,1.420000,98.312523
13,Albania,ALB,Europe & Central Asia,Upper middle income,2013,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,50.0,No,No,Yes,Yes,1.000000,88.298477
14,Albania,ALB,Europe & Central Asia,Upper middle income,2014,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,50.0,No,No,Yes,Yes,1.770000,105.165398
15,Albania,ALB,Europe & Central Asia,Upper middle income,2015,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,50.0,No,No,Yes,Yes,2.220000,102.982307
16,Albania,ALB,Europe & Central Asia,Upper middle income,2016,85.63,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,50.0,No,No,Yes,Yes,3.350000,104.641220
17,Albania,ALB,Europe & Central Asia,Upper middle income,2017,91.25,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,50.0,No,No,Yes,Yes,3.835544,104.833992
18,Algeria,DZA,Middle East & North Africa,Upper middle income,2009,55.00,75.0,No,Yes,Yes,...,No,Yes,No,25.0,No,No,No,Yes,1.632244,92.650978
19,Algeria,DZA,Middle East & North Africa,Upper middle income,2010,55.00,75.0,No,Yes,Yes,...,No,Yes,No,25.0,No,No,No,Yes,3.634145,95.257019
20,Algeria,DZA,Middle East & North Africa,Upper middle income,2011,55.00,75.0,No,Yes,Yes,...,No,Yes,No,25.0,No,No,No,Yes,2.891866,97.208069
21,Algeria,DZA,Middle East & North Africa,Upper middle income,2012,55.00,75.0,No,Yes,Yes,...,No,Yes,No,25.0,No,No,No,Yes,3.374769,101.158592
22,Algeria,DZA,Middle East & North Africa,Upper middle income,2013,55.00,75.0,No,Yes,Yes,...,No,Yes,No,25.0,No,No,No,Yes,2.767639,105.700691
23,Algeria,DZA,Middle East & North Africa,Upper middle income,2014,55.00,75.0,No,Yes,Yes,...,No,Yes,No,25.0,No,No,No,Yes,3.789121,108.752777
24,Algeria,DZA,Middle East & North Africa,Upper middle income,2015,55.00,75.0,No,Yes,Yes,...,No,Yes,No,25.0,No,No,No,Yes,3.763467,105.333527
25,Algeria,DZA,Middle East & North Africa,Upper middle income,2016,55.00,75.0,No,Yes,Yes,...,No,Yes,No,25.0,No,No,No,Yes,3.300000,105.371857
26,Algeria,DZA,Middle East & North Africa,Upper middle income,2017,57.50,75.0,No,Yes,Yes,...,No,Yes,No,25.0,No,No,No,Yes,1.600000,105.695236
27,Angola,AGO,Sub-Saharan Africa,Lower middle income,2009,65.00,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,25.0,No,No,Yes,No,0.858713,34.099152
28,Angola,AGO,Sub-Saharan Africa,Lower middle income,2010,71.25,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,75.0,Yes,Yes,Yes,No,4.859220,33.640591
29,Angola,AGO,Sub-Saharan Africa,Lower middle income,2011,71.25,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,75.0,Yes,Yes,Yes,No,3.471981,33.219440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1599,Vietnam,VNM,East Asia & Pacific,Lower middle income,2015,79.38,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,25.0,No,Yes,No,No,6.679289,103.771973
1600,Vietnam,VNM,East Asia & Pacific,Lower middle income,2016,79.38,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,25.0,No,Yes,No,No,6.210812,105.003029
1601,Vietnam,VNM,East Asia & Pacific,Lower middle income,2017,81.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,25.0,No,Yes,No,No,6.812246,NaN
1602,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2009,35.00,50.0,Yes,Yes,No,...,Yes,Yes,No,25.0,No,No,Yes,No,8.662535,89.163902
1603,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2010,35.00,50.0,Yes,Yes,No,...,Yes,Yes,No,25.0,No,No,Yes,No,8.099089,92.229187
1604,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2011,35.00,50.0,Yes,Yes,No,...,Yes,Yes,No,25.0,No,No,Yes,No,12.413635,91.903931
1605,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2012,35.00,50.0,Yes,Yes,No,...,Yes,Yes,No,25.0,No,No,Yes,No,6.284236,89.482590
1606,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2013,35.00,50.0,Yes,Yes,No,...,Yes,Yes,No,25.0,No,No,Yes,No,2.217422,93.972031
1607,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2014,35.00,50.0,Yes,Yes,No,...,Yes,Yes,No,25.0,No,No,Yes,No,-0.181891,95.460670
1608,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2015,35.00,50.0,Yes,Yes,No,...,Yes,Yes,No,25.0,No,No,Yes,No,3.428732,95.178917
1609,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2016,35.00,50.0,Yes,Yes,No,...,Yes,Yes,No,25.0,No,No,Yes,No,4.708435,93.381241
1610,West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income,2017,44.38,50.0,Yes,Yes,No,...,Yes,Yes,No,100.0,Yes,Yes,Yes,Yes,3.140237,96.417191
1611,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2009,63.75,75.0,No,Yes,Yes,...,Yes,Yes,No,75.0,Yes,Yes,Yes,No,9.220348,78.407333
1612,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2010,63.75,75.0,No,Yes,Yes,...,Yes,Yes,No,75.0,Yes,Yes,Yes,No,10.298206,99.939362
1613,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2011,63.75,75.0,No,Yes,Yes,...,Yes,Yes,No,75.0,Yes,Yes,Yes,No,5.564625,NaN
1614,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2012,63.75,75.0,No,Yes,Yes,...,Yes,Yes,No,75.0,Yes,Yes,Yes,No,7.597617,86.377579
1615,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2013,66.25,75.0,No,Yes,Yes,...,Yes,Yes,No,75.0,Yes,Yes,Yes,No,5.059376,77.591408
1616,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2014,66.25,75.0,No,Yes,Yes,...,Yes,Yes,No,75.0,Yes,Yes,Yes,No,4.695826,NaN
1617,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2015,66.25,75.0,No,Yes,Yes,...,Yes,Yes,No,75.0,Yes,Yes,Yes,No,2.919881,NaN
1618,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2016,66.25,75.0,No,Yes,Yes,...,Yes,Yes,No,75.0,Yes,Yes,Yes,No,3.757178,NaN
1619,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2017,78.75,75.0,No,Yes,Yes,...,Yes,Yes,No,75.0,Yes,Yes,Yes,No,3.403169,NaN
1620,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2009,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes,12.019561,NaN
1621,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2010,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes,19.675323,NaN
1622,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2011,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes,14.193913,NaN
1623,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2012,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes,16.665429,89.227951
1624,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2013,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes,1.989493,89.678162
1625,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2014,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes,2.376929,NaN
1626,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2015,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes,1.779873,NaN
1627,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2016,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes,0.755869,NaN
1628,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,2017,86.88,100.0,Yes,Yes,Yes,...,Yes,Yes,Yes,100.0,Yes,Yes,Yes,Yes,4.704035,NaN

In [129]:
df_all.to_csv("tab.csv")